-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_p_hls_fptosi_float_i32 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of swiglu_p_hls_fptosi_float_i32 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal xs_sign_reg_172 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_fu_88_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_177 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_887_reg_187 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal data_fu_40_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_60_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_64_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_52_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_78_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_82_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_96_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln18_fu_102_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_106_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_1_fu_114_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_74_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_118_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_122_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_128_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal val_fu_154_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_1_fu_159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_887_reg_187 <= shl_ln18_fu_128_p2(55 downto 24);
                tmp_reg_177 <= add_ln317_fu_82_p2(8 downto 8);
                tmp_s_reg_182 <= lshr_ln18_fu_122_p2(55 downto 24);
                xs_sign_reg_172 <= data_fu_40_p1(31 downto 31);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln317_fu_82_p2 <= std_logic_vector(unsigned(zext_ln317_fu_78_p1) + unsigned(ap_const_lv9_181));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        result_1_fu_159_p2 when (xs_sign_reg_172(0) = '1') else 
        val_fu_154_p3;
    data_fu_40_p1 <= x;
    lshr_ln18_fu_122_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_74_p1),to_integer(unsigned('0' & zext_ln18_fu_118_p1(31-1 downto 0)))));
    mantissa_fu_64_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_60_p1) & ap_const_lv1_0);
    result_1_fu_159_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_154_p3));
    select_ln18_fu_106_p3 <= 
        sext_ln18_fu_102_p1 when (tmp_fu_88_p3(0) = '1') else 
        add_ln317_fu_82_p2;
        sext_ln18_1_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_106_p3),32));

        sext_ln18_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_96_p2),9));

    shl_ln18_fu_128_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_74_p1),to_integer(unsigned('0' & zext_ln18_fu_118_p1(31-1 downto 0)))));
    sub_ln18_fu_96_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_52_p3));
    tmp_fu_88_p3 <= add_ln317_fu_82_p2(8 downto 8);
    trunc_ln342_fu_60_p1 <= data_fu_40_p1(23 - 1 downto 0);
    val_fu_154_p3 <= 
        tmp_s_reg_182 when (tmp_reg_177(0) = '1') else 
        tmp_887_reg_187;
    xs_exp_fu_52_p3 <= data_fu_40_p1(30 downto 23);
    zext_ln15_fu_74_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_64_p4),79));
    zext_ln18_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_114_p1),79));
    zext_ln317_fu_78_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_52_p3),9));
end behav;
