// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module swiglu_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln607,
        gate_0_address0,
        gate_0_ce0,
        gate_0_q0,
        gate_1_address0,
        gate_1_ce0,
        gate_1_q0,
        gate_2_address0,
        gate_2_ce0,
        gate_2_q0,
        gate_3_address0,
        gate_3_ce0,
        gate_3_q0,
        gate_4_address0,
        gate_4_ce0,
        gate_4_q0,
        gate_5_address0,
        gate_5_ce0,
        gate_5_q0,
        gate_6_address0,
        gate_6_ce0,
        gate_6_q0,
        gate_7_address0,
        gate_7_ce0,
        gate_7_q0,
        tmp_87,
        ql_buf_0_address0,
        ql_buf_0_ce0,
        ql_buf_0_q0,
        ql_buf_1_address0,
        ql_buf_1_ce0,
        ql_buf_1_q0,
        ql_buf_2_address0,
        ql_buf_2_ce0,
        ql_buf_2_q0,
        ql_buf_3_address0,
        ql_buf_3_ce0,
        ql_buf_3_q0,
        ql_buf_4_address0,
        ql_buf_4_ce0,
        ql_buf_4_q0,
        ql_buf_5_address0,
        ql_buf_5_ce0,
        ql_buf_5_q0,
        ql_buf_6_address0,
        ql_buf_6_ce0,
        ql_buf_6_q0,
        ql_buf_7_address0,
        ql_buf_7_ce0,
        ql_buf_7_q0,
        qh_buf_0_address0,
        qh_buf_0_ce0,
        qh_buf_0_q0,
        qh_buf_1_address0,
        qh_buf_1_ce0,
        qh_buf_1_q0,
        qh_buf_2_address0,
        qh_buf_2_ce0,
        qh_buf_2_q0,
        qh_buf_3_address0,
        qh_buf_3_ce0,
        qh_buf_3_q0,
        qh_buf_4_address0,
        qh_buf_4_ce0,
        qh_buf_4_q0,
        qh_buf_5_address0,
        qh_buf_5_ce0,
        qh_buf_5_q0,
        qh_buf_6_address0,
        qh_buf_6_ce0,
        qh_buf_6_q0,
        qh_buf_7_address0,
        qh_buf_7_ce0,
        qh_buf_7_q0,
        empty,
        tmp,
        tmp_s,
        tmp_65,
        tmp_66,
        acc_local_load_out,
        acc_local_load_out_ap_vld,
        acc_local_1_load_out,
        acc_local_1_load_out_ap_vld,
        acc_local_2_load_out,
        acc_local_2_load_out_ap_vld,
        acc_local_3_load_out,
        acc_local_3_load_out_ap_vld,
        acc_local_4_load_out,
        acc_local_4_load_out_ap_vld,
        acc_local_5_load_out,
        acc_local_5_load_out_ap_vld,
        acc_local_6_load_out,
        acc_local_6_load_out_ap_vld,
        acc_local_7_load_out,
        acc_local_7_load_out_ap_vld,
        acc_local_8_load_out,
        acc_local_8_load_out_ap_vld,
        acc_local_9_load_out,
        acc_local_9_load_out_ap_vld,
        acc_local_10_load_out,
        acc_local_10_load_out_ap_vld,
        acc_local_11_load_out,
        acc_local_11_load_out_ap_vld,
        acc_local_12_load_out,
        acc_local_12_load_out_ap_vld,
        acc_local_13_load_out,
        acc_local_13_load_out_ap_vld,
        acc_local_14_load_out,
        acc_local_14_load_out_ap_vld,
        acc_local_15_load_out,
        acc_local_15_load_out_ap_vld,
        acc_local_16_load_out,
        acc_local_16_load_out_ap_vld,
        acc_local_17_load_out,
        acc_local_17_load_out_ap_vld,
        acc_local_18_load_out,
        acc_local_18_load_out_ap_vld,
        acc_local_19_load_out,
        acc_local_19_load_out_ap_vld,
        acc_local_20_load_out,
        acc_local_20_load_out_ap_vld,
        acc_local_21_load_out,
        acc_local_21_load_out_ap_vld,
        acc_local_22_load_out,
        acc_local_22_load_out_ap_vld,
        acc_local_23_load_out,
        acc_local_23_load_out_ap_vld,
        acc_local_24_load_out,
        acc_local_24_load_out_ap_vld,
        acc_local_25_load_out,
        acc_local_25_load_out_ap_vld,
        acc_local_26_load_out,
        acc_local_26_load_out_ap_vld,
        acc_local_27_load_out,
        acc_local_27_load_out_ap_vld,
        acc_local_28_load_out,
        acc_local_28_load_out_ap_vld,
        acc_local_29_load_out,
        acc_local_29_load_out_ap_vld,
        acc_local_30_load_out,
        acc_local_30_load_out_ap_vld,
        acc_local_31_load_out,
        acc_local_31_load_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] zext_ln607;
output  [9:0] gate_0_address0;
output   gate_0_ce0;
input  [7:0] gate_0_q0;
output  [9:0] gate_1_address0;
output   gate_1_ce0;
input  [7:0] gate_1_q0;
output  [9:0] gate_2_address0;
output   gate_2_ce0;
input  [7:0] gate_2_q0;
output  [9:0] gate_3_address0;
output   gate_3_ce0;
input  [7:0] gate_3_q0;
output  [9:0] gate_4_address0;
output   gate_4_ce0;
input  [7:0] gate_4_q0;
output  [9:0] gate_5_address0;
output   gate_5_ce0;
input  [7:0] gate_5_q0;
output  [9:0] gate_6_address0;
output   gate_6_ce0;
input  [7:0] gate_6_q0;
output  [9:0] gate_7_address0;
output   gate_7_ce0;
input  [7:0] gate_7_q0;
input  [1:0] tmp_87;
output  [4:0] ql_buf_0_address0;
output   ql_buf_0_ce0;
input  [127:0] ql_buf_0_q0;
output  [4:0] ql_buf_1_address0;
output   ql_buf_1_ce0;
input  [127:0] ql_buf_1_q0;
output  [4:0] ql_buf_2_address0;
output   ql_buf_2_ce0;
input  [127:0] ql_buf_2_q0;
output  [4:0] ql_buf_3_address0;
output   ql_buf_3_ce0;
input  [127:0] ql_buf_3_q0;
output  [4:0] ql_buf_4_address0;
output   ql_buf_4_ce0;
input  [127:0] ql_buf_4_q0;
output  [4:0] ql_buf_5_address0;
output   ql_buf_5_ce0;
input  [127:0] ql_buf_5_q0;
output  [4:0] ql_buf_6_address0;
output   ql_buf_6_ce0;
input  [127:0] ql_buf_6_q0;
output  [4:0] ql_buf_7_address0;
output   ql_buf_7_ce0;
input  [127:0] ql_buf_7_q0;
output  [3:0] qh_buf_0_address0;
output   qh_buf_0_ce0;
input  [127:0] qh_buf_0_q0;
output  [3:0] qh_buf_1_address0;
output   qh_buf_1_ce0;
input  [127:0] qh_buf_1_q0;
output  [3:0] qh_buf_2_address0;
output   qh_buf_2_ce0;
input  [127:0] qh_buf_2_q0;
output  [3:0] qh_buf_3_address0;
output   qh_buf_3_ce0;
input  [127:0] qh_buf_3_q0;
output  [3:0] qh_buf_4_address0;
output   qh_buf_4_ce0;
input  [127:0] qh_buf_4_q0;
output  [3:0] qh_buf_5_address0;
output   qh_buf_5_ce0;
input  [127:0] qh_buf_5_q0;
output  [3:0] qh_buf_6_address0;
output   qh_buf_6_ce0;
input  [127:0] qh_buf_6_q0;
output  [3:0] qh_buf_7_address0;
output   qh_buf_7_ce0;
input  [127:0] qh_buf_7_q0;
input  [0:0] empty;
input  [127:0] tmp;
input  [127:0] tmp_s;
input  [127:0] tmp_65;
input  [127:0] tmp_66;
output  [31:0] acc_local_load_out;
output   acc_local_load_out_ap_vld;
output  [31:0] acc_local_1_load_out;
output   acc_local_1_load_out_ap_vld;
output  [31:0] acc_local_2_load_out;
output   acc_local_2_load_out_ap_vld;
output  [31:0] acc_local_3_load_out;
output   acc_local_3_load_out_ap_vld;
output  [31:0] acc_local_4_load_out;
output   acc_local_4_load_out_ap_vld;
output  [31:0] acc_local_5_load_out;
output   acc_local_5_load_out_ap_vld;
output  [31:0] acc_local_6_load_out;
output   acc_local_6_load_out_ap_vld;
output  [31:0] acc_local_7_load_out;
output   acc_local_7_load_out_ap_vld;
output  [31:0] acc_local_8_load_out;
output   acc_local_8_load_out_ap_vld;
output  [31:0] acc_local_9_load_out;
output   acc_local_9_load_out_ap_vld;
output  [31:0] acc_local_10_load_out;
output   acc_local_10_load_out_ap_vld;
output  [31:0] acc_local_11_load_out;
output   acc_local_11_load_out_ap_vld;
output  [31:0] acc_local_12_load_out;
output   acc_local_12_load_out_ap_vld;
output  [31:0] acc_local_13_load_out;
output   acc_local_13_load_out_ap_vld;
output  [31:0] acc_local_14_load_out;
output   acc_local_14_load_out_ap_vld;
output  [31:0] acc_local_15_load_out;
output   acc_local_15_load_out_ap_vld;
output  [31:0] acc_local_16_load_out;
output   acc_local_16_load_out_ap_vld;
output  [31:0] acc_local_17_load_out;
output   acc_local_17_load_out_ap_vld;
output  [31:0] acc_local_18_load_out;
output   acc_local_18_load_out_ap_vld;
output  [31:0] acc_local_19_load_out;
output   acc_local_19_load_out_ap_vld;
output  [31:0] acc_local_20_load_out;
output   acc_local_20_load_out_ap_vld;
output  [31:0] acc_local_21_load_out;
output   acc_local_21_load_out_ap_vld;
output  [31:0] acc_local_22_load_out;
output   acc_local_22_load_out_ap_vld;
output  [31:0] acc_local_23_load_out;
output   acc_local_23_load_out_ap_vld;
output  [31:0] acc_local_24_load_out;
output   acc_local_24_load_out_ap_vld;
output  [31:0] acc_local_25_load_out;
output   acc_local_25_load_out_ap_vld;
output  [31:0] acc_local_26_load_out;
output   acc_local_26_load_out_ap_vld;
output  [31:0] acc_local_27_load_out;
output   acc_local_27_load_out_ap_vld;
output  [31:0] acc_local_28_load_out;
output   acc_local_28_load_out_ap_vld;
output  [31:0] acc_local_29_load_out;
output   acc_local_29_load_out_ap_vld;
output  [31:0] acc_local_30_load_out;
output   acc_local_30_load_out_ap_vld;
output  [31:0] acc_local_31_load_out;
output   acc_local_31_load_out_ap_vld;

reg ap_idle;
reg acc_local_load_out_ap_vld;
reg acc_local_1_load_out_ap_vld;
reg acc_local_2_load_out_ap_vld;
reg acc_local_3_load_out_ap_vld;
reg acc_local_4_load_out_ap_vld;
reg acc_local_5_load_out_ap_vld;
reg acc_local_6_load_out_ap_vld;
reg acc_local_7_load_out_ap_vld;
reg acc_local_8_load_out_ap_vld;
reg acc_local_9_load_out_ap_vld;
reg acc_local_10_load_out_ap_vld;
reg acc_local_11_load_out_ap_vld;
reg acc_local_12_load_out_ap_vld;
reg acc_local_13_load_out_ap_vld;
reg acc_local_14_load_out_ap_vld;
reg acc_local_15_load_out_ap_vld;
reg acc_local_16_load_out_ap_vld;
reg acc_local_17_load_out_ap_vld;
reg acc_local_18_load_out_ap_vld;
reg acc_local_19_load_out_ap_vld;
reg acc_local_20_load_out_ap_vld;
reg acc_local_21_load_out_ap_vld;
reg acc_local_22_load_out_ap_vld;
reg acc_local_23_load_out_ap_vld;
reg acc_local_24_load_out_ap_vld;
reg acc_local_25_load_out_ap_vld;
reg acc_local_26_load_out_ap_vld;
reg acc_local_27_load_out_ap_vld;
reg acc_local_28_load_out_ap_vld;
reg acc_local_29_load_out_ap_vld;
reg acc_local_30_load_out_ap_vld;
reg acc_local_31_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln588_fu_1104_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] n_2_reg_2591;
reg   [8:0] n_2_reg_2591_pp0_iter1_reg;
reg   [0:0] icmp_ln588_reg_2601;
reg   [0:0] icmp_ln588_reg_2601_pp0_iter1_reg;
reg   [0:0] icmp_ln588_reg_2601_pp0_iter2_reg;
reg   [0:0] icmp_ln588_reg_2601_pp0_iter3_reg;
reg   [0:0] icmp_ln588_reg_2601_pp0_iter4_reg;
reg   [0:0] icmp_ln588_reg_2601_pp0_iter5_reg;
wire   [63:0] zext_ln595_fu_1134_p1;
reg   [63:0] zext_ln595_reg_2605;
reg   [63:0] zext_ln595_reg_2605_pp0_iter1_reg;
wire   [63:0] zext_ln600_fu_1162_p1;
reg   [63:0] zext_ln600_reg_2641;
reg   [63:0] zext_ln600_reg_2641_pp0_iter1_reg;
wire   [7:0] sc_b_fu_1190_p3;
reg   [7:0] sc_b_reg_2677;
reg   [7:0] sc_b_reg_2677_pp0_iter1_reg;
reg  signed [7:0] sc_b_reg_2677_pp0_iter2_reg;
wire   [7:0] sc_b_1_fu_1198_p3;
reg   [7:0] sc_b_1_reg_2682;
reg   [7:0] sc_b_1_reg_2682_pp0_iter1_reg;
reg  signed [7:0] sc_b_1_reg_2682_pp0_iter2_reg;
wire   [7:0] sc_b_2_fu_1206_p3;
reg   [7:0] sc_b_2_reg_2687;
reg   [7:0] sc_b_2_reg_2687_pp0_iter1_reg;
reg  signed [7:0] sc_b_2_reg_2687_pp0_iter2_reg;
wire   [7:0] sc_b_3_fu_1214_p3;
reg   [7:0] sc_b_3_reg_2692;
reg   [7:0] sc_b_3_reg_2692_pp0_iter1_reg;
reg  signed [7:0] sc_b_3_reg_2692_pp0_iter2_reg;
wire   [63:0] zext_ln607_2_fu_1235_p1;
reg   [63:0] zext_ln607_2_reg_2697;
reg   [127:0] ql_buf_1_load_reg_2717;
reg   [127:0] ql_buf_5_load_reg_2722;
reg   [127:0] ql_buf_2_load_reg_2727;
reg   [127:0] ql_buf_6_load_reg_2732;
reg   [127:0] ql_buf_3_load_reg_2737;
reg   [127:0] ql_buf_7_load_reg_2742;
reg   [127:0] qh_buf_1_load_reg_2747;
reg   [127:0] qh_buf_5_load_reg_2752;
reg   [127:0] qh_buf_2_load_reg_2757;
reg   [127:0] qh_buf_6_load_reg_2762;
reg   [127:0] qh_buf_3_load_reg_2767;
reg   [127:0] qh_buf_7_load_reg_2772;
wire   [2:0] empty_729_fu_1241_p1;
reg   [2:0] empty_729_reg_2807;
reg   [2:0] empty_729_reg_2807_pp0_iter3_reg;
reg   [2:0] empty_729_reg_2807_pp0_iter4_reg;
reg   [2:0] empty_729_reg_2807_pp0_iter5_reg;
reg   [2:0] empty_729_reg_2807_pp0_iter6_reg;
wire   [0:0] empty_730_fu_1244_p1;
reg   [0:0] empty_730_reg_2815;
reg   [0:0] empty_730_reg_2815_pp0_iter3_reg;
wire   [6:0] mul_fu_1256_p3;
reg   [6:0] mul_reg_2830;
reg   [6:0] mul_reg_2830_pp0_iter3_reg;
wire   [6:0] mul1_fu_1284_p3;
reg   [6:0] mul1_reg_2845;
reg   [6:0] mul1_reg_2845_pp0_iter3_reg;
wire   [7:0] shl_cast_fu_1292_p1;
reg   [7:0] shl_cast_reg_2850;
reg   [7:0] shl_cast_reg_2850_pp0_iter3_reg;
wire   [7:0] gv_fu_1296_p3;
reg  signed [7:0] gv_reg_2855;
wire   [3:0] select_ln597_1_fu_1330_p3;
reg   [3:0] select_ln597_1_reg_2860;
wire   [3:0] select_ln597_2_fu_1365_p3;
reg   [3:0] select_ln597_2_reg_2865;
wire   [3:0] select_ln597_3_fu_1400_p3;
reg   [3:0] select_ln597_3_reg_2870;
reg   [0:0] bit_sel4_reg_2875;
wire   [0:0] trunc_ln608_1_fu_1435_p1;
reg   [0:0] trunc_ln608_1_reg_2880;
reg   [0:0] bit_sel1_reg_2885;
wire   [0:0] trunc_ln608_2_fu_1466_p1;
reg   [0:0] trunc_ln608_2_reg_2890;
reg   [0:0] bit_sel_reg_2895;
wire   [0:0] trunc_ln608_3_fu_1497_p1;
reg   [0:0] trunc_ln608_3_reg_2900;
wire   [127:0] select_ln595_fu_1519_p3;
reg   [127:0] select_ln595_reg_2905;
wire   [127:0] select_ln600_fu_1526_p3;
reg   [127:0] select_ln600_reg_2910;
wire   [15:0] mul_ln608_fu_1539_p2;
reg  signed [15:0] mul_ln608_reg_2915;
wire   [7:0] gv_4_fu_1585_p3;
reg  signed [7:0] gv_4_reg_2920;
wire   [7:0] gv_5_fu_1592_p3;
reg  signed [7:0] gv_5_reg_2925;
wire   [7:0] gv_3_fu_1599_p3;
reg  signed [7:0] gv_3_reg_2930;
wire   [13:0] mul_ln608_2_fu_1626_p2;
reg  signed [13:0] mul_ln608_2_reg_2935;
wire   [13:0] mul_ln608_4_fu_1632_p2;
reg  signed [13:0] mul_ln608_4_reg_2940;
wire   [13:0] mul_ln608_6_fu_1638_p2;
reg  signed [13:0] mul_ln608_6_reg_2945;
wire  signed [31:0] tmp_70_fu_1759_p19;
wire  signed [31:0] tmp_71_fu_1822_p19;
wire  signed [31:0] tmp_72_fu_1885_p19;
wire  signed [31:0] tmp_73_fu_1948_p19;
wire    ap_block_pp0_stage0;
reg   [8:0] n_fu_226;
wire   [8:0] add_ln588_fu_1110_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_n_2;
reg   [31:0] acc_local_31_fu_230;
wire  signed [31:0] grp_fu_2291_p3;
reg   [31:0] ap_sig_allocacmp_acc_local_31_load_1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [31:0] acc_local_30_fu_234;
reg   [31:0] ap_sig_allocacmp_acc_local_30_load_1;
reg   [31:0] acc_local_29_fu_238;
reg   [31:0] ap_sig_allocacmp_acc_local_29_load_1;
reg   [31:0] acc_local_28_fu_242;
reg   [31:0] ap_sig_allocacmp_acc_local_28_load_1;
reg   [31:0] acc_local_27_fu_246;
reg   [31:0] ap_sig_allocacmp_acc_local_27_load_1;
reg   [31:0] acc_local_26_fu_250;
reg   [31:0] ap_sig_allocacmp_acc_local_26_load_1;
reg   [31:0] acc_local_25_fu_254;
reg   [31:0] ap_sig_allocacmp_acc_local_25_load_1;
reg   [31:0] acc_local_24_fu_258;
reg   [31:0] ap_sig_allocacmp_acc_local_24_load_1;
reg   [31:0] acc_local_23_fu_262;
wire  signed [31:0] grp_fu_2275_p3;
reg   [31:0] ap_sig_allocacmp_acc_local_23_load_1;
reg   [31:0] acc_local_22_fu_266;
reg   [31:0] ap_sig_allocacmp_acc_local_22_load_1;
reg   [31:0] acc_local_21_fu_270;
reg   [31:0] ap_sig_allocacmp_acc_local_21_load_1;
reg   [31:0] acc_local_20_fu_274;
reg   [31:0] ap_sig_allocacmp_acc_local_20_load_1;
reg   [31:0] acc_local_19_fu_278;
reg   [31:0] ap_sig_allocacmp_acc_local_19_load_1;
reg   [31:0] acc_local_18_fu_282;
reg   [31:0] ap_sig_allocacmp_acc_local_18_load_1;
reg   [31:0] acc_local_17_fu_286;
reg   [31:0] ap_sig_allocacmp_acc_local_17_load_1;
reg   [31:0] acc_local_16_fu_290;
reg   [31:0] ap_sig_allocacmp_acc_local_16_load_1;
reg   [31:0] acc_local_15_fu_294;
wire  signed [31:0] grp_fu_2259_p3;
reg   [31:0] ap_sig_allocacmp_acc_local_15_load_1;
reg   [31:0] acc_local_14_fu_298;
reg   [31:0] ap_sig_allocacmp_acc_local_14_load_1;
reg   [31:0] acc_local_13_fu_302;
reg   [31:0] ap_sig_allocacmp_acc_local_13_load_1;
reg   [31:0] acc_local_12_fu_306;
reg   [31:0] ap_sig_allocacmp_acc_local_12_load_1;
reg   [31:0] acc_local_11_fu_310;
reg   [31:0] ap_sig_allocacmp_acc_local_11_load_1;
reg   [31:0] acc_local_10_fu_314;
reg   [31:0] ap_sig_allocacmp_acc_local_10_load_1;
reg   [31:0] acc_local_9_fu_318;
reg   [31:0] ap_sig_allocacmp_acc_local_9_load_1;
reg   [31:0] acc_local_8_fu_322;
reg   [31:0] ap_sig_allocacmp_acc_local_8_load_1;
reg   [31:0] acc_local_7_fu_326;
wire  signed [31:0] grp_fu_2243_p3;
reg   [31:0] ap_sig_allocacmp_acc_local_7_load_1;
reg   [31:0] acc_local_6_fu_330;
reg   [31:0] ap_sig_allocacmp_acc_local_6_load_1;
reg   [31:0] acc_local_5_fu_334;
reg   [31:0] ap_sig_allocacmp_acc_local_5_load_1;
reg   [31:0] acc_local_4_fu_338;
reg   [31:0] ap_sig_allocacmp_acc_local_4_load_1;
reg   [31:0] acc_local_3_fu_342;
reg   [31:0] ap_sig_allocacmp_acc_local_3_load_1;
reg   [31:0] acc_local_2_fu_346;
reg   [31:0] ap_sig_allocacmp_acc_local_2_load_1;
reg   [31:0] acc_local_1_fu_350;
reg   [31:0] ap_sig_allocacmp_acc_local_1_load_1;
reg   [31:0] acc_local_fu_354;
reg   [31:0] ap_sig_allocacmp_acc_local_load_1;
wire    ap_block_pp0_stage0_01001;
reg    ql_buf_1_ce0_local;
reg    ql_buf_5_ce0_local;
reg    ql_buf_2_ce0_local;
reg    ql_buf_6_ce0_local;
reg    ql_buf_3_ce0_local;
reg    ql_buf_7_ce0_local;
reg    qh_buf_1_ce0_local;
reg    qh_buf_5_ce0_local;
reg    qh_buf_2_ce0_local;
reg    qh_buf_6_ce0_local;
reg    qh_buf_3_ce0_local;
reg    qh_buf_7_ce0_local;
reg    gate_0_ce0_local;
reg    gate_4_ce0_local;
reg    ql_buf_0_ce0_local;
reg    ql_buf_4_ce0_local;
reg    qh_buf_0_ce0_local;
reg    qh_buf_4_ce0_local;
reg    gate_1_ce0_local;
reg    gate_5_ce0_local;
reg    gate_2_ce0_local;
reg    gate_6_ce0_local;
reg    gate_3_ce0_local;
reg    gate_7_ce0_local;
wire   [2:0] tmp_84_fu_1116_p4;
wire   [4:0] tmp_85_fu_1126_p3;
wire   [1:0] tmp_88_fu_1144_p4;
wire   [3:0] tmp_89_fu_1154_p3;
wire   [3:0] tmp_91_fu_1172_p4;
wire   [6:0] mul2_fu_1182_p3;
wire   [9:0] zext_ln607_1_fu_1227_p1;
wire   [9:0] add_ln607_fu_1230_p2;
wire   [3:0] tmp_86_fu_1247_p4;
wire   [1:0] empty_731_fu_1264_p1;
wire   [3:0] tmp_90_fu_1275_p4;
wire   [2:0] p_cast_fu_1267_p3;
wire   [127:0] ql_byte_1_fu_1308_p1;
wire   [7:0] ql_byte_1_fu_1308_p3;
wire   [3:0] tmp_93_fu_1316_p4;
wire   [3:0] trunc_ln597_1_fu_1326_p1;
wire   [127:0] ql_byte_2_fu_1343_p1;
wire   [7:0] ql_byte_2_fu_1343_p3;
wire   [3:0] tmp_94_fu_1351_p4;
wire   [3:0] trunc_ln597_2_fu_1361_p1;
wire   [127:0] ql_byte_3_fu_1378_p1;
wire   [7:0] ql_byte_3_fu_1378_p3;
wire   [3:0] tmp_95_fu_1386_p4;
wire   [3:0] trunc_ln597_3_fu_1396_p1;
wire   [127:0] qh_byte_1_fu_1413_p1;
wire   [7:0] qh_byte_1_fu_1413_p3;
wire   [7:0] lshr_ln602_1_fu_1421_p2;
wire   [127:0] qh_byte_2_fu_1444_p1;
wire   [7:0] qh_byte_2_fu_1444_p3;
wire   [7:0] lshr_ln602_2_fu_1452_p2;
wire   [127:0] qh_byte_3_fu_1475_p1;
wire   [7:0] qh_byte_3_fu_1475_p3;
wire   [7:0] lshr_ln602_3_fu_1483_p2;
wire   [0:0] xor_ln608_fu_1551_p2;
wire  signed [5:0] xor_ln608_1_fu_1556_p4;
wire   [0:0] xor_ln608_5_fu_1568_p2;
wire  signed [5:0] xor_ln608_2_fu_1573_p4;
wire   [0:0] xor_ln608_6_fu_1606_p2;
wire  signed [5:0] xor_ln608_3_fu_1611_p4;
wire   [7:0] ql_byte_fu_1644_p3;
wire   [3:0] tmp_92_fu_1650_p4;
wire   [3:0] trunc_ln597_fu_1660_p1;
wire   [7:0] qh_byte_fu_1671_p3;
wire   [7:0] lshr_ln602_fu_1677_p2;
wire   [0:0] bit_sel7_fu_1682_p3;
wire   [0:0] xor_ln608_4_fu_1690_p2;
wire   [0:0] trunc_ln608_fu_1696_p1;
wire   [3:0] select_ln597_fu_1664_p3;
wire  signed [5:0] xor_ln_fu_1700_p4;
wire   [31:0] tmp_70_fu_1759_p17;
wire   [31:0] tmp_71_fu_1822_p17;
wire   [31:0] tmp_72_fu_1885_p17;
wire   [31:0] tmp_73_fu_1948_p17;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [7:0] sc_b_fu_1190_p0;
wire   [7:0] sc_b_1_fu_1198_p0;
wire   [7:0] sc_b_2_fu_1206_p0;
wire   [7:0] sc_b_3_fu_1214_p0;
wire   [7:0] ql_byte_1_fu_1308_p0;
wire   [7:0] ql_byte_2_fu_1343_p0;
wire   [7:0] ql_byte_3_fu_1378_p0;
wire   [7:0] qh_byte_1_fu_1413_p0;
wire   [7:0] qh_byte_2_fu_1444_p0;
wire   [7:0] qh_byte_3_fu_1475_p0;
wire   [7:0] ql_byte_fu_1644_p0;
wire   [7:0] qh_byte_fu_1671_p0;
wire   [2:0] tmp_70_fu_1759_p1;
wire   [2:0] tmp_70_fu_1759_p3;
wire   [2:0] tmp_70_fu_1759_p5;
wire   [2:0] tmp_70_fu_1759_p7;
wire  signed [2:0] tmp_70_fu_1759_p9;
wire  signed [2:0] tmp_70_fu_1759_p11;
wire  signed [2:0] tmp_70_fu_1759_p13;
wire  signed [2:0] tmp_70_fu_1759_p15;
wire   [2:0] tmp_71_fu_1822_p1;
wire   [2:0] tmp_71_fu_1822_p3;
wire   [2:0] tmp_71_fu_1822_p5;
wire   [2:0] tmp_71_fu_1822_p7;
wire  signed [2:0] tmp_71_fu_1822_p9;
wire  signed [2:0] tmp_71_fu_1822_p11;
wire  signed [2:0] tmp_71_fu_1822_p13;
wire  signed [2:0] tmp_71_fu_1822_p15;
wire   [2:0] tmp_72_fu_1885_p1;
wire   [2:0] tmp_72_fu_1885_p3;
wire   [2:0] tmp_72_fu_1885_p5;
wire   [2:0] tmp_72_fu_1885_p7;
wire  signed [2:0] tmp_72_fu_1885_p9;
wire  signed [2:0] tmp_72_fu_1885_p11;
wire  signed [2:0] tmp_72_fu_1885_p13;
wire  signed [2:0] tmp_72_fu_1885_p15;
wire   [2:0] tmp_73_fu_1948_p1;
wire   [2:0] tmp_73_fu_1948_p3;
wire   [2:0] tmp_73_fu_1948_p5;
wire   [2:0] tmp_73_fu_1948_p7;
wire  signed [2:0] tmp_73_fu_1948_p9;
wire  signed [2:0] tmp_73_fu_1948_p11;
wire  signed [2:0] tmp_73_fu_1948_p13;
wire  signed [2:0] tmp_73_fu_1948_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 n_fu_226 = 9'd0;
#0 acc_local_31_fu_230 = 32'd0;
#0 acc_local_30_fu_234 = 32'd0;
#0 acc_local_29_fu_238 = 32'd0;
#0 acc_local_28_fu_242 = 32'd0;
#0 acc_local_27_fu_246 = 32'd0;
#0 acc_local_26_fu_250 = 32'd0;
#0 acc_local_25_fu_254 = 32'd0;
#0 acc_local_24_fu_258 = 32'd0;
#0 acc_local_23_fu_262 = 32'd0;
#0 acc_local_22_fu_266 = 32'd0;
#0 acc_local_21_fu_270 = 32'd0;
#0 acc_local_20_fu_274 = 32'd0;
#0 acc_local_19_fu_278 = 32'd0;
#0 acc_local_18_fu_282 = 32'd0;
#0 acc_local_17_fu_286 = 32'd0;
#0 acc_local_16_fu_290 = 32'd0;
#0 acc_local_15_fu_294 = 32'd0;
#0 acc_local_14_fu_298 = 32'd0;
#0 acc_local_13_fu_302 = 32'd0;
#0 acc_local_12_fu_306 = 32'd0;
#0 acc_local_11_fu_310 = 32'd0;
#0 acc_local_10_fu_314 = 32'd0;
#0 acc_local_9_fu_318 = 32'd0;
#0 acc_local_8_fu_322 = 32'd0;
#0 acc_local_7_fu_326 = 32'd0;
#0 acc_local_6_fu_330 = 32'd0;
#0 acc_local_5_fu_334 = 32'd0;
#0 acc_local_4_fu_338 = 32'd0;
#0 acc_local_3_fu_342 = 32'd0;
#0 acc_local_2_fu_346 = 32'd0;
#0 acc_local_1_fu_350 = 32'd0;
#0 acc_local_fu_354 = 32'd0;
#0 ap_done_reg = 1'b0;
end

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2075(
    .din(tmp),
    .sel(mul2_fu_1182_p3),
    .dout(sc_b_fu_1190_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2076(
    .din(tmp_s),
    .sel(mul2_fu_1182_p3),
    .dout(sc_b_1_fu_1198_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2077(
    .din(tmp_65),
    .sel(mul2_fu_1182_p3),
    .dout(sc_b_2_fu_1206_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2078(
    .din(tmp_66),
    .sel(mul2_fu_1182_p3),
    .dout(sc_b_3_fu_1214_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2079(
    .din(ql_byte_1_fu_1308_p1),
    .sel(mul_fu_1256_p3),
    .dout(ql_byte_1_fu_1308_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2080(
    .din(ql_byte_2_fu_1343_p1),
    .sel(mul_fu_1256_p3),
    .dout(ql_byte_2_fu_1343_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2081(
    .din(ql_byte_3_fu_1378_p1),
    .sel(mul_fu_1256_p3),
    .dout(ql_byte_3_fu_1378_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2082(
    .din(qh_byte_1_fu_1413_p1),
    .sel(mul1_fu_1284_p3),
    .dout(qh_byte_1_fu_1413_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2083(
    .din(qh_byte_2_fu_1444_p1),
    .sel(mul1_fu_1284_p3),
    .dout(qh_byte_2_fu_1444_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2084(
    .din(qh_byte_3_fu_1475_p1),
    .sel(mul1_fu_1284_p3),
    .dout(qh_byte_3_fu_1475_p3)
);

swiglu_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U2085(
    .din0(gv_reg_2855),
    .din1(sc_b_reg_2677_pp0_iter2_reg),
    .dout(mul_ln608_fu_1539_p2)
);

swiglu_mul_8s_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_1_1_U2086(
    .din0(sc_b_1_reg_2682_pp0_iter2_reg),
    .din1(xor_ln608_1_fu_1556_p4),
    .dout(mul_ln608_2_fu_1626_p2)
);

swiglu_mul_8s_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_1_1_U2087(
    .din0(sc_b_2_reg_2687_pp0_iter2_reg),
    .din1(xor_ln608_2_fu_1573_p4),
    .dout(mul_ln608_4_fu_1632_p2)
);

swiglu_mul_8s_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_1_1_U2088(
    .din0(sc_b_3_reg_2692_pp0_iter2_reg),
    .din1(xor_ln608_3_fu_1611_p4),
    .dout(mul_ln608_6_fu_1638_p2)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2089(
    .din(select_ln595_reg_2905),
    .sel(mul_reg_2830_pp0_iter3_reg),
    .dout(ql_byte_fu_1644_p3)
);

swiglu_partselect_8ns_128ns_7ns_8_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ),
    .DATA1WIDTH( 8 ))
partselect_8ns_128ns_7ns_8_1_1_U2090(
    .din(select_ln600_reg_2910),
    .sel(mul1_reg_2845_pp0_iter3_reg),
    .dout(qh_byte_fu_1671_p3)
);

(* dissolve_hierarchy = "yes" *) swiglu_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2091(
    .din0(ap_sig_allocacmp_acc_local_load_1),
    .din1(ap_sig_allocacmp_acc_local_1_load_1),
    .din2(ap_sig_allocacmp_acc_local_2_load_1),
    .din3(ap_sig_allocacmp_acc_local_3_load_1),
    .din4(ap_sig_allocacmp_acc_local_4_load_1),
    .din5(ap_sig_allocacmp_acc_local_5_load_1),
    .din6(ap_sig_allocacmp_acc_local_6_load_1),
    .din7(ap_sig_allocacmp_acc_local_7_load_1),
    .def(tmp_70_fu_1759_p17),
    .sel(empty_729_reg_2807_pp0_iter5_reg),
    .dout(tmp_70_fu_1759_p19)
);

(* dissolve_hierarchy = "yes" *) swiglu_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2092(
    .din0(ap_sig_allocacmp_acc_local_8_load_1),
    .din1(ap_sig_allocacmp_acc_local_9_load_1),
    .din2(ap_sig_allocacmp_acc_local_10_load_1),
    .din3(ap_sig_allocacmp_acc_local_11_load_1),
    .din4(ap_sig_allocacmp_acc_local_12_load_1),
    .din5(ap_sig_allocacmp_acc_local_13_load_1),
    .din6(ap_sig_allocacmp_acc_local_14_load_1),
    .din7(ap_sig_allocacmp_acc_local_15_load_1),
    .def(tmp_71_fu_1822_p17),
    .sel(empty_729_reg_2807_pp0_iter5_reg),
    .dout(tmp_71_fu_1822_p19)
);

(* dissolve_hierarchy = "yes" *) swiglu_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2093(
    .din0(ap_sig_allocacmp_acc_local_16_load_1),
    .din1(ap_sig_allocacmp_acc_local_17_load_1),
    .din2(ap_sig_allocacmp_acc_local_18_load_1),
    .din3(ap_sig_allocacmp_acc_local_19_load_1),
    .din4(ap_sig_allocacmp_acc_local_20_load_1),
    .din5(ap_sig_allocacmp_acc_local_21_load_1),
    .din6(ap_sig_allocacmp_acc_local_22_load_1),
    .din7(ap_sig_allocacmp_acc_local_23_load_1),
    .def(tmp_72_fu_1885_p17),
    .sel(empty_729_reg_2807_pp0_iter5_reg),
    .dout(tmp_72_fu_1885_p19)
);

(* dissolve_hierarchy = "yes" *) swiglu_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2094(
    .din0(ap_sig_allocacmp_acc_local_24_load_1),
    .din1(ap_sig_allocacmp_acc_local_25_load_1),
    .din2(ap_sig_allocacmp_acc_local_26_load_1),
    .din3(ap_sig_allocacmp_acc_local_27_load_1),
    .din4(ap_sig_allocacmp_acc_local_28_load_1),
    .din5(ap_sig_allocacmp_acc_local_29_load_1),
    .din6(ap_sig_allocacmp_acc_local_30_load_1),
    .din7(ap_sig_allocacmp_acc_local_31_load_1),
    .def(tmp_73_fu_1948_p17),
    .sel(empty_729_reg_2807_pp0_iter5_reg),
    .dout(tmp_73_fu_1948_p19)
);

swiglu_mac_muladd_16s_6s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_6s_32s_32_4_1_U2095(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln608_reg_2915),
    .din1(xor_ln_fu_1700_p4),
    .din2(tmp_70_fu_1759_p19),
    .ce(1'b1),
    .dout(grp_fu_2243_p3)
);

swiglu_mac_muladd_14s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_14s_8s_32s_32_4_1_U2096(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln608_2_reg_2935),
    .din1(gv_4_reg_2920),
    .din2(tmp_71_fu_1822_p19),
    .ce(1'b1),
    .dout(grp_fu_2259_p3)
);

swiglu_mac_muladd_14s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_14s_8s_32s_32_4_1_U2097(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln608_4_reg_2940),
    .din1(gv_5_reg_2925),
    .din2(tmp_72_fu_1885_p19),
    .ce(1'b1),
    .dout(grp_fu_2275_p3)
);

swiglu_mac_muladd_14s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_14s_8s_32s_32_4_1_U2098(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln608_6_reg_2945),
    .din1(gv_3_reg_2930),
    .din2(tmp_73_fu_1948_p19),
    .ce(1'b1),
    .dout(grp_fu_2291_p3)
);

swiglu_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_10_fu_314 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_10_fu_314 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_11_fu_310 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_11_fu_310 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_12_fu_306 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_12_fu_306 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_13_fu_302 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_13_fu_302 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_14_fu_298 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_14_fu_298 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_15_fu_294 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_15_fu_294 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_16_fu_290 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_16_fu_290 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_17_fu_286 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_17_fu_286 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_18_fu_282 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_18_fu_282 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_19_fu_278 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_19_fu_278 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_1_fu_350 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_1_fu_350 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_20_fu_274 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_20_fu_274 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_21_fu_270 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_21_fu_270 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_22_fu_266 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_22_fu_266 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_23_fu_262 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_23_fu_262 <= grp_fu_2275_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_24_fu_258 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_24_fu_258 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_25_fu_254 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_25_fu_254 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_26_fu_250 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_26_fu_250 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_27_fu_246 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_27_fu_246 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_28_fu_242 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_28_fu_242 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_29_fu_238 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_29_fu_238 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_2_fu_346 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_2_fu_346 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_30_fu_234 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_30_fu_234 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_31_fu_230 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_31_fu_230 <= grp_fu_2291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_3_fu_342 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_3_fu_342 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_4_fu_338 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_4_fu_338 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_5_fu_334 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_5_fu_334 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_6_fu_330 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_6_fu_330 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_7_fu_326 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_7_fu_326 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_8_fu_322 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_8_fu_322 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_9_fu_318 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_9_fu_318 <= grp_fu_2259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_local_fu_354 <= 32'd0;
        end else if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            acc_local_fu_354 <= grp_fu_2243_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln588_fu_1104_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_226 <= add_ln588_fu_1110_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_226 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln588_reg_2601 <= icmp_ln588_fu_1104_p2;
        icmp_ln588_reg_2601_pp0_iter1_reg <= icmp_ln588_reg_2601;
        n_2_reg_2591 <= ap_sig_allocacmp_n_2;
        n_2_reg_2591_pp0_iter1_reg <= n_2_reg_2591;
        qh_buf_1_load_reg_2747 <= qh_buf_1_q0;
        qh_buf_2_load_reg_2757 <= qh_buf_2_q0;
        qh_buf_3_load_reg_2767 <= qh_buf_3_q0;
        qh_buf_5_load_reg_2752 <= qh_buf_5_q0;
        qh_buf_6_load_reg_2762 <= qh_buf_6_q0;
        qh_buf_7_load_reg_2772 <= qh_buf_7_q0;
        ql_buf_1_load_reg_2717 <= ql_buf_1_q0;
        ql_buf_2_load_reg_2727 <= ql_buf_2_q0;
        ql_buf_3_load_reg_2737 <= ql_buf_3_q0;
        ql_buf_5_load_reg_2722 <= ql_buf_5_q0;
        ql_buf_6_load_reg_2732 <= ql_buf_6_q0;
        ql_buf_7_load_reg_2742 <= ql_buf_7_q0;
        sc_b_1_reg_2682 <= sc_b_1_fu_1198_p3;
        sc_b_1_reg_2682_pp0_iter1_reg <= sc_b_1_reg_2682;
        sc_b_2_reg_2687 <= sc_b_2_fu_1206_p3;
        sc_b_2_reg_2687_pp0_iter1_reg <= sc_b_2_reg_2687;
        sc_b_3_reg_2692 <= sc_b_3_fu_1214_p3;
        sc_b_3_reg_2692_pp0_iter1_reg <= sc_b_3_reg_2692;
        sc_b_reg_2677 <= sc_b_fu_1190_p3;
        sc_b_reg_2677_pp0_iter1_reg <= sc_b_reg_2677;
        zext_ln595_reg_2605[4 : 0] <= zext_ln595_fu_1134_p1[4 : 0];
        zext_ln595_reg_2605_pp0_iter1_reg[4 : 0] <= zext_ln595_reg_2605[4 : 0];
        zext_ln600_reg_2641[3 : 0] <= zext_ln600_fu_1162_p1[3 : 0];
        zext_ln600_reg_2641_pp0_iter1_reg[3 : 0] <= zext_ln600_reg_2641[3 : 0];
        zext_ln607_2_reg_2697[9 : 0] <= zext_ln607_2_fu_1235_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        bit_sel1_reg_2885 <= lshr_ln602_2_fu_1452_p2[32'd1];
        bit_sel4_reg_2875 <= lshr_ln602_1_fu_1421_p2[32'd1];
        bit_sel_reg_2895 <= lshr_ln602_3_fu_1483_p2[32'd1];
        empty_729_reg_2807 <= empty_729_fu_1241_p1;
        empty_729_reg_2807_pp0_iter3_reg <= empty_729_reg_2807;
        empty_729_reg_2807_pp0_iter4_reg <= empty_729_reg_2807_pp0_iter3_reg;
        empty_729_reg_2807_pp0_iter5_reg <= empty_729_reg_2807_pp0_iter4_reg;
        empty_729_reg_2807_pp0_iter6_reg <= empty_729_reg_2807_pp0_iter5_reg;
        empty_730_reg_2815 <= empty_730_fu_1244_p1;
        empty_730_reg_2815_pp0_iter3_reg <= empty_730_reg_2815;
        gv_3_reg_2930 <= gv_3_fu_1599_p3;
        gv_4_reg_2920 <= gv_4_fu_1585_p3;
        gv_5_reg_2925 <= gv_5_fu_1592_p3;
        gv_reg_2855 <= gv_fu_1296_p3;
        icmp_ln588_reg_2601_pp0_iter2_reg <= icmp_ln588_reg_2601_pp0_iter1_reg;
        icmp_ln588_reg_2601_pp0_iter3_reg <= icmp_ln588_reg_2601_pp0_iter2_reg;
        icmp_ln588_reg_2601_pp0_iter4_reg <= icmp_ln588_reg_2601_pp0_iter3_reg;
        icmp_ln588_reg_2601_pp0_iter5_reg <= icmp_ln588_reg_2601_pp0_iter4_reg;
        mul1_reg_2845[6 : 3] <= mul1_fu_1284_p3[6 : 3];
        mul1_reg_2845_pp0_iter3_reg[6 : 3] <= mul1_reg_2845[6 : 3];
        mul_ln608_2_reg_2935 <= mul_ln608_2_fu_1626_p2;
        mul_ln608_4_reg_2940 <= mul_ln608_4_fu_1632_p2;
        mul_ln608_6_reg_2945 <= mul_ln608_6_fu_1638_p2;
        mul_ln608_reg_2915 <= mul_ln608_fu_1539_p2;
        mul_reg_2830[6 : 3] <= mul_fu_1256_p3[6 : 3];
        mul_reg_2830_pp0_iter3_reg[6 : 3] <= mul_reg_2830[6 : 3];
        sc_b_1_reg_2682_pp0_iter2_reg <= sc_b_1_reg_2682_pp0_iter1_reg;
        sc_b_2_reg_2687_pp0_iter2_reg <= sc_b_2_reg_2687_pp0_iter1_reg;
        sc_b_3_reg_2692_pp0_iter2_reg <= sc_b_3_reg_2692_pp0_iter1_reg;
        sc_b_reg_2677_pp0_iter2_reg <= sc_b_reg_2677_pp0_iter1_reg;
        select_ln595_reg_2905 <= select_ln595_fu_1519_p3;
        select_ln597_1_reg_2860 <= select_ln597_1_fu_1330_p3;
        select_ln597_2_reg_2865 <= select_ln597_2_fu_1365_p3;
        select_ln597_3_reg_2870 <= select_ln597_3_fu_1400_p3;
        select_ln600_reg_2910 <= select_ln600_fu_1526_p3;
        shl_cast_reg_2850[2 : 1] <= shl_cast_fu_1292_p1[2 : 1];
        shl_cast_reg_2850_pp0_iter3_reg[2 : 1] <= shl_cast_reg_2850[2 : 1];
        trunc_ln608_1_reg_2880 <= trunc_ln608_1_fu_1435_p1;
        trunc_ln608_2_reg_2890 <= trunc_ln608_2_fu_1466_p1;
        trunc_ln608_3_reg_2900 <= trunc_ln608_3_fu_1497_p1;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_10_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_10_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_11_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_11_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_12_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_12_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_13_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_13_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_14_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_14_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_15_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_15_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_16_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_16_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_17_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_17_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_18_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_18_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_19_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_19_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_1_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_20_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_20_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_21_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_21_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_22_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_22_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_23_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_23_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_24_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_24_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_25_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_25_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_26_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_26_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_27_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_27_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_28_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_28_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_29_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_29_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_2_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_30_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_30_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_31_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_31_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_3_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_4_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_5_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_6_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_7_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_8_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_8_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_9_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_9_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln588_reg_2601_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_local_load_out_ap_vld = 1'b1;
    end else begin
        acc_local_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln588_fu_1104_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_10_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_10_load_1 = acc_local_10_fu_314;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_11_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_11_load_1 = acc_local_11_fu_310;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_12_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_12_load_1 = acc_local_12_fu_306;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_13_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_13_load_1 = acc_local_13_fu_302;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_14_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_14_load_1 = acc_local_14_fu_298;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_15_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_15_load_1 = acc_local_15_fu_294;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_16_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_16_load_1 = acc_local_16_fu_290;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_17_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_17_load_1 = acc_local_17_fu_286;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_18_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_18_load_1 = acc_local_18_fu_282;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_19_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_19_load_1 = acc_local_19_fu_278;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_1_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_1_load_1 = acc_local_1_fu_350;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_20_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_20_load_1 = acc_local_20_fu_274;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_21_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_21_load_1 = acc_local_21_fu_270;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_22_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_22_load_1 = acc_local_22_fu_266;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_23_load_1 = grp_fu_2275_p3;
    end else begin
        ap_sig_allocacmp_acc_local_23_load_1 = acc_local_23_fu_262;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_24_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_24_load_1 = acc_local_24_fu_258;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_25_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_25_load_1 = acc_local_25_fu_254;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_26_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_26_load_1 = acc_local_26_fu_250;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_27_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_27_load_1 = acc_local_27_fu_246;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_28_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_28_load_1 = acc_local_28_fu_242;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_29_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_29_load_1 = acc_local_29_fu_238;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_2_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_2_load_1 = acc_local_2_fu_346;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_30_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_30_load_1 = acc_local_30_fu_234;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_31_load_1 = grp_fu_2291_p3;
    end else begin
        ap_sig_allocacmp_acc_local_31_load_1 = acc_local_31_fu_230;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_3_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_3_load_1 = acc_local_3_fu_342;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_4_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_4_load_1 = acc_local_4_fu_338;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_5_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_5_load_1 = acc_local_5_fu_334;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_6_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_6_load_1 = acc_local_6_fu_330;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_7_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_7_load_1 = acc_local_7_fu_326;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_8_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_8_load_1 = acc_local_8_fu_322;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_9_load_1 = grp_fu_2259_p3;
    end else begin
        ap_sig_allocacmp_acc_local_9_load_1 = acc_local_9_fu_318;
    end
end

always @ (*) begin
    if (((empty_729_reg_2807_pp0_iter6_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_acc_local_load_1 = grp_fu_2243_p3;
    end else begin
        ap_sig_allocacmp_acc_local_load_1 = acc_local_fu_354;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_n_2 = n_fu_226;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gate_0_ce0_local = 1'b1;
    end else begin
        gate_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gate_1_ce0_local = 1'b1;
    end else begin
        gate_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gate_2_ce0_local = 1'b1;
    end else begin
        gate_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gate_3_ce0_local = 1'b1;
    end else begin
        gate_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gate_4_ce0_local = 1'b1;
    end else begin
        gate_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gate_5_ce0_local = 1'b1;
    end else begin
        gate_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gate_6_ce0_local = 1'b1;
    end else begin
        gate_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gate_7_ce0_local = 1'b1;
    end else begin
        gate_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        qh_buf_0_ce0_local = 1'b1;
    end else begin
        qh_buf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qh_buf_1_ce0_local = 1'b1;
    end else begin
        qh_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qh_buf_2_ce0_local = 1'b1;
    end else begin
        qh_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qh_buf_3_ce0_local = 1'b1;
    end else begin
        qh_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        qh_buf_4_ce0_local = 1'b1;
    end else begin
        qh_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qh_buf_5_ce0_local = 1'b1;
    end else begin
        qh_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qh_buf_6_ce0_local = 1'b1;
    end else begin
        qh_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qh_buf_7_ce0_local = 1'b1;
    end else begin
        qh_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ql_buf_0_ce0_local = 1'b1;
    end else begin
        ql_buf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ql_buf_1_ce0_local = 1'b1;
    end else begin
        ql_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ql_buf_2_ce0_local = 1'b1;
    end else begin
        ql_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ql_buf_3_ce0_local = 1'b1;
    end else begin
        ql_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ql_buf_4_ce0_local = 1'b1;
    end else begin
        ql_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ql_buf_5_ce0_local = 1'b1;
    end else begin
        ql_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ql_buf_6_ce0_local = 1'b1;
    end else begin
        ql_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ql_buf_7_ce0_local = 1'b1;
    end else begin
        ql_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_local_10_load_out = acc_local_10_fu_314;

assign acc_local_11_load_out = acc_local_11_fu_310;

assign acc_local_12_load_out = acc_local_12_fu_306;

assign acc_local_13_load_out = acc_local_13_fu_302;

assign acc_local_14_load_out = acc_local_14_fu_298;

assign acc_local_15_load_out = acc_local_15_fu_294;

assign acc_local_16_load_out = acc_local_16_fu_290;

assign acc_local_17_load_out = acc_local_17_fu_286;

assign acc_local_18_load_out = acc_local_18_fu_282;

assign acc_local_19_load_out = acc_local_19_fu_278;

assign acc_local_1_load_out = acc_local_1_fu_350;

assign acc_local_20_load_out = acc_local_20_fu_274;

assign acc_local_21_load_out = acc_local_21_fu_270;

assign acc_local_22_load_out = acc_local_22_fu_266;

assign acc_local_23_load_out = acc_local_23_fu_262;

assign acc_local_24_load_out = acc_local_24_fu_258;

assign acc_local_25_load_out = acc_local_25_fu_254;

assign acc_local_26_load_out = acc_local_26_fu_250;

assign acc_local_27_load_out = acc_local_27_fu_246;

assign acc_local_28_load_out = acc_local_28_fu_242;

assign acc_local_29_load_out = acc_local_29_fu_238;

assign acc_local_2_load_out = acc_local_2_fu_346;

assign acc_local_30_load_out = acc_local_30_fu_234;

assign acc_local_31_load_out = acc_local_31_fu_230;

assign acc_local_3_load_out = acc_local_3_fu_342;

assign acc_local_4_load_out = acc_local_4_fu_338;

assign acc_local_5_load_out = acc_local_5_fu_334;

assign acc_local_6_load_out = acc_local_6_fu_330;

assign acc_local_7_load_out = acc_local_7_fu_326;

assign acc_local_8_load_out = acc_local_8_fu_322;

assign acc_local_9_load_out = acc_local_9_fu_318;

assign acc_local_load_out = acc_local_fu_354;

assign add_ln588_fu_1110_p2 = (ap_sig_allocacmp_n_2 + 9'd1);

assign add_ln607_fu_1230_p2 = (zext_ln607 + zext_ln607_1_fu_1227_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel7_fu_1682_p3 = lshr_ln602_fu_1677_p2[32'd1];

assign empty_729_fu_1241_p1 = n_2_reg_2591_pp0_iter1_reg[2:0];

assign empty_730_fu_1244_p1 = n_2_reg_2591_pp0_iter1_reg[0:0];

assign empty_731_fu_1264_p1 = n_2_reg_2591_pp0_iter1_reg[1:0];

assign gate_0_address0 = zext_ln607_2_fu_1235_p1;

assign gate_0_ce0 = gate_0_ce0_local;

assign gate_1_address0 = zext_ln607_2_reg_2697;

assign gate_1_ce0 = gate_1_ce0_local;

assign gate_2_address0 = zext_ln607_2_reg_2697;

assign gate_2_ce0 = gate_2_ce0_local;

assign gate_3_address0 = zext_ln607_2_reg_2697;

assign gate_3_ce0 = gate_3_ce0_local;

assign gate_4_address0 = zext_ln607_2_fu_1235_p1;

assign gate_4_ce0 = gate_4_ce0_local;

assign gate_5_address0 = zext_ln607_2_reg_2697;

assign gate_5_ce0 = gate_5_ce0_local;

assign gate_6_address0 = zext_ln607_2_reg_2697;

assign gate_6_ce0 = gate_6_ce0_local;

assign gate_7_address0 = zext_ln607_2_reg_2697;

assign gate_7_ce0 = gate_7_ce0_local;

assign gv_3_fu_1599_p3 = ((empty[0:0] == 1'b1) ? gate_7_q0 : gate_3_q0);

assign gv_4_fu_1585_p3 = ((empty[0:0] == 1'b1) ? gate_5_q0 : gate_1_q0);

assign gv_5_fu_1592_p3 = ((empty[0:0] == 1'b1) ? gate_6_q0 : gate_2_q0);

assign gv_fu_1296_p3 = ((empty[0:0] == 1'b1) ? gate_4_q0 : gate_0_q0);

assign icmp_ln588_fu_1104_p2 = ((ap_sig_allocacmp_n_2 == 9'd256) ? 1'b1 : 1'b0);

assign lshr_ln602_1_fu_1421_p2 = qh_byte_1_fu_1413_p3 >> shl_cast_fu_1292_p1;

assign lshr_ln602_2_fu_1452_p2 = qh_byte_2_fu_1444_p3 >> shl_cast_fu_1292_p1;

assign lshr_ln602_3_fu_1483_p2 = qh_byte_3_fu_1475_p3 >> shl_cast_fu_1292_p1;

assign lshr_ln602_fu_1677_p2 = qh_byte_fu_1671_p3 >> shl_cast_reg_2850_pp0_iter3_reg;

assign mul1_fu_1284_p3 = {{tmp_90_fu_1275_p4}, {3'd0}};

assign mul2_fu_1182_p3 = {{tmp_91_fu_1172_p4}, {3'd0}};

assign mul_fu_1256_p3 = {{tmp_86_fu_1247_p4}, {3'd0}};

assign p_cast_fu_1267_p3 = {{empty_731_fu_1264_p1}, {1'd0}};

assign qh_buf_0_address0 = zext_ln600_reg_2641_pp0_iter1_reg;

assign qh_buf_0_ce0 = qh_buf_0_ce0_local;

assign qh_buf_1_address0 = zext_ln600_fu_1162_p1;

assign qh_buf_1_ce0 = qh_buf_1_ce0_local;

assign qh_buf_2_address0 = zext_ln600_fu_1162_p1;

assign qh_buf_2_ce0 = qh_buf_2_ce0_local;

assign qh_buf_3_address0 = zext_ln600_fu_1162_p1;

assign qh_buf_3_ce0 = qh_buf_3_ce0_local;

assign qh_buf_4_address0 = zext_ln600_reg_2641_pp0_iter1_reg;

assign qh_buf_4_ce0 = qh_buf_4_ce0_local;

assign qh_buf_5_address0 = zext_ln600_fu_1162_p1;

assign qh_buf_5_ce0 = qh_buf_5_ce0_local;

assign qh_buf_6_address0 = zext_ln600_fu_1162_p1;

assign qh_buf_6_ce0 = qh_buf_6_ce0_local;

assign qh_buf_7_address0 = zext_ln600_fu_1162_p1;

assign qh_buf_7_ce0 = qh_buf_7_ce0_local;

assign qh_byte_1_fu_1413_p1 = ((empty[0:0] == 1'b1) ? qh_buf_5_load_reg_2752 : qh_buf_1_load_reg_2747);

assign qh_byte_2_fu_1444_p1 = ((empty[0:0] == 1'b1) ? qh_buf_6_load_reg_2762 : qh_buf_2_load_reg_2757);

assign qh_byte_3_fu_1475_p1 = ((empty[0:0] == 1'b1) ? qh_buf_7_load_reg_2772 : qh_buf_3_load_reg_2767);

assign ql_buf_0_address0 = zext_ln595_reg_2605_pp0_iter1_reg;

assign ql_buf_0_ce0 = ql_buf_0_ce0_local;

assign ql_buf_1_address0 = zext_ln595_fu_1134_p1;

assign ql_buf_1_ce0 = ql_buf_1_ce0_local;

assign ql_buf_2_address0 = zext_ln595_fu_1134_p1;

assign ql_buf_2_ce0 = ql_buf_2_ce0_local;

assign ql_buf_3_address0 = zext_ln595_fu_1134_p1;

assign ql_buf_3_ce0 = ql_buf_3_ce0_local;

assign ql_buf_4_address0 = zext_ln595_reg_2605_pp0_iter1_reg;

assign ql_buf_4_ce0 = ql_buf_4_ce0_local;

assign ql_buf_5_address0 = zext_ln595_fu_1134_p1;

assign ql_buf_5_ce0 = ql_buf_5_ce0_local;

assign ql_buf_6_address0 = zext_ln595_fu_1134_p1;

assign ql_buf_6_ce0 = ql_buf_6_ce0_local;

assign ql_buf_7_address0 = zext_ln595_fu_1134_p1;

assign ql_buf_7_ce0 = ql_buf_7_ce0_local;

assign ql_byte_1_fu_1308_p1 = ((empty[0:0] == 1'b1) ? ql_buf_5_load_reg_2722 : ql_buf_1_load_reg_2717);

assign ql_byte_2_fu_1343_p1 = ((empty[0:0] == 1'b1) ? ql_buf_6_load_reg_2732 : ql_buf_2_load_reg_2727);

assign ql_byte_3_fu_1378_p1 = ((empty[0:0] == 1'b1) ? ql_buf_7_load_reg_2742 : ql_buf_3_load_reg_2737);

assign select_ln595_fu_1519_p3 = ((empty[0:0] == 1'b1) ? ql_buf_4_q0 : ql_buf_0_q0);

assign select_ln597_1_fu_1330_p3 = ((empty_730_fu_1244_p1[0:0] == 1'b1) ? tmp_93_fu_1316_p4 : trunc_ln597_1_fu_1326_p1);

assign select_ln597_2_fu_1365_p3 = ((empty_730_fu_1244_p1[0:0] == 1'b1) ? tmp_94_fu_1351_p4 : trunc_ln597_2_fu_1361_p1);

assign select_ln597_3_fu_1400_p3 = ((empty_730_fu_1244_p1[0:0] == 1'b1) ? tmp_95_fu_1386_p4 : trunc_ln597_3_fu_1396_p1);

assign select_ln597_fu_1664_p3 = ((empty_730_reg_2815_pp0_iter3_reg[0:0] == 1'b1) ? tmp_92_fu_1650_p4 : trunc_ln597_fu_1660_p1);

assign select_ln600_fu_1526_p3 = ((empty[0:0] == 1'b1) ? qh_buf_4_q0 : qh_buf_0_q0);

assign shl_cast_fu_1292_p1 = p_cast_fu_1267_p3;

assign tmp_70_fu_1759_p17 = 'bx;

assign tmp_71_fu_1822_p17 = 'bx;

assign tmp_72_fu_1885_p17 = 'bx;

assign tmp_73_fu_1948_p17 = 'bx;

assign tmp_84_fu_1116_p4 = {{ap_sig_allocacmp_n_2[7:5]}};

assign tmp_85_fu_1126_p3 = {{tmp_87}, {tmp_84_fu_1116_p4}};

assign tmp_86_fu_1247_p4 = {{n_2_reg_2591_pp0_iter1_reg[4:1]}};

assign tmp_88_fu_1144_p4 = {{ap_sig_allocacmp_n_2[7:6]}};

assign tmp_89_fu_1154_p3 = {{tmp_87}, {tmp_88_fu_1144_p4}};

assign tmp_90_fu_1275_p4 = {{n_2_reg_2591_pp0_iter1_reg[5:2]}};

assign tmp_91_fu_1172_p4 = {{ap_sig_allocacmp_n_2[7:4]}};

assign tmp_92_fu_1650_p4 = {{ql_byte_fu_1644_p3[7:4]}};

assign tmp_93_fu_1316_p4 = {{ql_byte_1_fu_1308_p3[7:4]}};

assign tmp_94_fu_1351_p4 = {{ql_byte_2_fu_1343_p3[7:4]}};

assign tmp_95_fu_1386_p4 = {{ql_byte_3_fu_1378_p3[7:4]}};

assign trunc_ln597_1_fu_1326_p1 = ql_byte_1_fu_1308_p3[3:0];

assign trunc_ln597_2_fu_1361_p1 = ql_byte_2_fu_1343_p3[3:0];

assign trunc_ln597_3_fu_1396_p1 = ql_byte_3_fu_1378_p3[3:0];

assign trunc_ln597_fu_1660_p1 = ql_byte_fu_1644_p3[3:0];

assign trunc_ln608_1_fu_1435_p1 = lshr_ln602_1_fu_1421_p2[0:0];

assign trunc_ln608_2_fu_1466_p1 = lshr_ln602_2_fu_1452_p2[0:0];

assign trunc_ln608_3_fu_1497_p1 = lshr_ln602_3_fu_1483_p2[0:0];

assign trunc_ln608_fu_1696_p1 = lshr_ln602_fu_1677_p2[0:0];

assign xor_ln608_1_fu_1556_p4 = {{{xor_ln608_fu_1551_p2}, {trunc_ln608_1_reg_2880}}, {select_ln597_1_reg_2860}};

assign xor_ln608_2_fu_1573_p4 = {{{xor_ln608_5_fu_1568_p2}, {trunc_ln608_2_reg_2890}}, {select_ln597_2_reg_2865}};

assign xor_ln608_3_fu_1611_p4 = {{{xor_ln608_6_fu_1606_p2}, {trunc_ln608_3_reg_2900}}, {select_ln597_3_reg_2870}};

assign xor_ln608_4_fu_1690_p2 = (bit_sel7_fu_1682_p3 ^ 1'd1);

assign xor_ln608_5_fu_1568_p2 = (bit_sel1_reg_2885 ^ 1'd1);

assign xor_ln608_6_fu_1606_p2 = (bit_sel_reg_2895 ^ 1'd1);

assign xor_ln608_fu_1551_p2 = (bit_sel4_reg_2875 ^ 1'd1);

assign xor_ln_fu_1700_p4 = {{{xor_ln608_4_fu_1690_p2}, {trunc_ln608_fu_1696_p1}}, {select_ln597_fu_1664_p3}};

assign zext_ln595_fu_1134_p1 = tmp_85_fu_1126_p3;

assign zext_ln600_fu_1162_p1 = tmp_89_fu_1154_p3;

assign zext_ln607_1_fu_1227_p1 = n_2_reg_2591;

assign zext_ln607_2_fu_1235_p1 = add_ln607_fu_1230_p2;

always @ (posedge ap_clk) begin
    zext_ln595_reg_2605[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln595_reg_2605_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln600_reg_2641[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln600_reg_2641_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln607_2_reg_2697[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    mul_reg_2830[2:0] <= 3'b000;
    mul_reg_2830_pp0_iter3_reg[2:0] <= 3'b000;
    mul1_reg_2845[2:0] <= 3'b000;
    mul1_reg_2845_pp0_iter3_reg[2:0] <= 3'b000;
    shl_cast_reg_2850[0] <= 1'b0;
    shl_cast_reg_2850[7:3] <= 5'b00000;
    shl_cast_reg_2850_pp0_iter3_reg[0] <= 1'b0;
    shl_cast_reg_2850_pp0_iter3_reg[7:3] <= 5'b00000;
end

endmodule //swiglu_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP
