// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module swiglu_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        W,
        W_c_din,
        W_c_full_n,
        W_c_write,
        W_c_num_data_valid,
        W_c_fifo_cap,
        V,
        V_c_din,
        V_c_full_n,
        V_c_write,
        V_c_num_data_valid,
        V_c_fifo_cap,
        W_down,
        W_down_c_din,
        W_down_c_full_n,
        W_down_c_write,
        W_down_c_num_data_valid,
        W_down_c_fifo_cap,
        out_batch,
        out_batch_c_din,
        out_batch_c_full_n,
        out_batch_c_write,
        out_batch_c_num_data_valid,
        out_batch_c_fifo_cap,
        down_quant_mode,
        down_quant_mode_c_din,
        down_quant_mode_c_full_n,
        down_quant_mode_c_write,
        down_quant_mode_c_num_data_valid,
        down_quant_mode_c_fifo_cap,
        x_scale,
        x_scale_c_din,
        x_scale_c_full_n,
        x_scale_c_write,
        x_scale_c_num_data_valid,
        x_scale_c_fifo_cap,
        x_scale_c1_din,
        x_scale_c1_full_n,
        x_scale_c1_write,
        x_scale_c1_num_data_valid,
        x_scale_c1_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] W;
output  [7:0] W_c_din;
input   W_c_full_n;
output   W_c_write;
input  [2:0] W_c_num_data_valid;
input  [2:0] W_c_fifo_cap;
input  [7:0] V;
output  [7:0] V_c_din;
input   V_c_full_n;
output   V_c_write;
input  [2:0] V_c_num_data_valid;
input  [2:0] V_c_fifo_cap;
input  [7:0] W_down;
output  [7:0] W_down_c_din;
input   W_down_c_full_n;
output   W_down_c_write;
input  [3:0] W_down_c_num_data_valid;
input  [3:0] W_down_c_fifo_cap;
input  [63:0] out_batch;
output  [63:0] out_batch_c_din;
input   out_batch_c_full_n;
output   out_batch_c_write;
input  [3:0] out_batch_c_num_data_valid;
input  [3:0] out_batch_c_fifo_cap;
input  [31:0] down_quant_mode;
output  [31:0] down_quant_mode_c_din;
input   down_quant_mode_c_full_n;
output   down_quant_mode_c_write;
input  [3:0] down_quant_mode_c_num_data_valid;
input  [3:0] down_quant_mode_c_fifo_cap;
input  [31:0] x_scale;
output  [31:0] x_scale_c_din;
input   x_scale_c_full_n;
output   x_scale_c_write;
input  [2:0] x_scale_c_num_data_valid;
input  [2:0] x_scale_c_fifo_cap;
output  [31:0] x_scale_c1_din;
input   x_scale_c1_full_n;
output   x_scale_c1_write;
input  [2:0] x_scale_c1_num_data_valid;
input  [2:0] x_scale_c1_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg W_c_write;
reg V_c_write;
reg W_down_c_write;
reg out_batch_c_write;
reg down_quant_mode_c_write;
reg x_scale_c_write;
reg x_scale_c1_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    W_c_blk_n;
reg    V_c_blk_n;
reg    W_down_c_blk_n;
reg    out_batch_c_blk_n;
reg    down_quant_mode_c_blk_n;
reg    x_scale_c_blk_n;
reg    x_scale_c1_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        V_c_blk_n = V_c_full_n;
    end else begin
        V_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        V_c_write = 1'b1;
    end else begin
        V_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        W_c_blk_n = W_c_full_n;
    end else begin
        W_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        W_c_write = 1'b1;
    end else begin
        W_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        W_down_c_blk_n = W_down_c_full_n;
    end else begin
        W_down_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        W_down_c_write = 1'b1;
    end else begin
        W_down_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        down_quant_mode_c_blk_n = down_quant_mode_c_full_n;
    end else begin
        down_quant_mode_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        down_quant_mode_c_write = 1'b1;
    end else begin
        down_quant_mode_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_batch_c_blk_n = out_batch_c_full_n;
    end else begin
        out_batch_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        out_batch_c_write = 1'b1;
    end else begin
        out_batch_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_scale_c1_blk_n = x_scale_c1_full_n;
    end else begin
        x_scale_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_scale_c1_write = 1'b1;
    end else begin
        x_scale_c1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_scale_c_blk_n = x_scale_c_full_n;
    end else begin
        x_scale_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_scale_c_write = 1'b1;
    end else begin
        x_scale_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign V_c_din = V;

assign W_c_din = W;

assign W_down_c_din = W_down;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (x_scale_c1_full_n == 1'b0) | (x_scale_c_full_n == 1'b0) | (down_quant_mode_c_full_n == 1'b0) | (out_batch_c_full_n == 1'b0) | (1'b0 == W_down_c_full_n) | (1'b0 == V_c_full_n) | (1'b0 == W_c_full_n) | (ap_done_reg == 1'b1));
end

assign down_quant_mode_c_din = down_quant_mode;

assign out_batch_c_din = out_batch;

assign x_scale_c1_din = x_scale;

assign x_scale_c_din = x_scale;

endmodule //swiglu_entry_proc
