// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module swiglu_fp16_to_fp32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] h;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln33_fu_48_p2;
reg   [0:0] icmp_ln33_reg_375;
wire   [9:0] m_fu_82_p3;
reg   [9:0] m_reg_380;
wire   [0:0] tmp_146_fu_98_p3;
reg   [0:0] tmp_146_reg_386;
wire   [5:0] e_16_fu_114_p3;
reg   [5:0] e_16_reg_391;
wire   [9:0] m_20_fu_187_p3;
reg   [9:0] m_20_reg_397;
wire    ap_CS_fsm_state2;
wire   [5:0] e_20_fu_195_p3;
reg   [5:0] e_20_reg_403;
reg   [0:0] tmp_149_reg_409;
wire   [9:0] m_22_fu_221_p3;
reg   [9:0] m_22_reg_415;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_150_fu_233_p3;
reg   [0:0] tmp_150_reg_421;
wire   [5:0] e_24_fu_247_p3;
reg   [5:0] e_24_reg_426;
wire   [6:0] trunc_ln39_fu_70_p1;
wire   [0:0] tmp_fu_54_p3;
wire   [9:0] st_fu_62_p3;
wire   [9:0] sf_fu_74_p3;
wire   [5:0] e_fu_90_p3;
wire   [5:0] e_15_fu_106_p3;
wire   [9:0] m_15_fu_122_p2;
wire   [9:0] m_16_fu_127_p3;
wire   [0:0] tmp_147_fu_133_p3;
wire   [9:0] m_17_fu_141_p2;
wire   [5:0] e_17_fu_147_p2;
wire   [9:0] m_18_fu_152_p3;
wire   [5:0] e_18_fu_160_p3;
wire   [0:0] tmp_148_fu_167_p3;
wire   [9:0] m_19_fu_175_p2;
wire   [5:0] e_19_fu_181_p2;
wire   [9:0] m_21_fu_211_p2;
wire   [5:0] e_21_fu_216_p2;
wire   [5:0] e_22_fu_227_p3;
wire   [5:0] e_23_fu_241_p2;
wire    ap_CS_fsm_state4;
wire   [9:0] m_23_fu_255_p2;
wire   [9:0] m_24_fu_260_p3;
wire   [0:0] tmp_151_fu_266_p3;
wire   [9:0] m_25_fu_274_p2;
wire   [5:0] e_25_fu_280_p2;
wire   [9:0] m_26_fu_285_p3;
wire   [7:0] trunc_ln39_2_fu_308_p1;
wire   [5:0] e_26_fu_293_p3;
wire   [0:0] tmp_152_fu_300_p3;
wire   [5:0] e_27_fu_320_p2;
wire   [8:0] trunc_ln41_fu_334_p1;
wire   [8:0] m_27_fu_312_p3;
wire   [5:0] e_28_fu_326_p3;
wire   [8:0] select_ln39_fu_338_p3;
wire   [28:0] f32_fu_346_p4;
wire   [28:0] f32_4_fu_356_p3;
wire  signed [29:0] sext_ln32_fu_363_p1;
wire   [31:0] zext_ln32_fu_367_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        e_16_reg_391[1 : 0] <= e_16_fu_114_p3[1 : 0];
        icmp_ln33_reg_375 <= icmp_ln33_fu_48_p2;
        m_reg_380[9 : 2] <= m_fu_82_p3[9 : 2];
        tmp_146_reg_386 <= m_fu_82_p3[32'd9];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        e_20_reg_403 <= e_20_fu_195_p3;
        m_20_reg_397 <= m_20_fu_187_p3;
        tmp_149_reg_409 <= m_20_fu_187_p3[32'd9];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        e_24_reg_426 <= e_24_fu_247_p3;
        m_22_reg_415 <= m_22_fu_221_p3;
        tmp_150_reg_421 <= m_22_fu_221_p3[32'd9];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return = zext_ln32_fu_367_p1;

assign e_15_fu_106_p3 = ((tmp_fu_54_p3[0:0] == 1'b1) ? 6'd45 : 6'd44);

assign e_16_fu_114_p3 = ((tmp_146_fu_98_p3[0:0] == 1'b1) ? e_fu_90_p3 : e_15_fu_106_p3);

assign e_17_fu_147_p2 = ($signed(e_16_reg_391) + $signed(6'd63));

assign e_18_fu_160_p3 = ((tmp_147_fu_133_p3[0:0] == 1'b1) ? e_16_reg_391 : e_17_fu_147_p2);

assign e_19_fu_181_p2 = ($signed(e_18_fu_160_p3) + $signed(6'd63));

assign e_20_fu_195_p3 = ((tmp_148_fu_167_p3[0:0] == 1'b1) ? e_18_fu_160_p3 : e_19_fu_181_p2);

assign e_21_fu_216_p2 = ($signed(e_20_reg_403) + $signed(6'd63));

assign e_22_fu_227_p3 = ((tmp_149_reg_409[0:0] == 1'b1) ? e_20_reg_403 : e_21_fu_216_p2);

assign e_23_fu_241_p2 = ($signed(e_22_fu_227_p3) + $signed(6'd63));

assign e_24_fu_247_p3 = ((tmp_150_fu_233_p3[0:0] == 1'b1) ? e_22_fu_227_p3 : e_23_fu_241_p2);

assign e_25_fu_280_p2 = ($signed(e_24_reg_426) + $signed(6'd63));

assign e_26_fu_293_p3 = ((tmp_151_fu_266_p3[0:0] == 1'b1) ? e_24_reg_426 : e_25_fu_280_p2);

assign e_27_fu_320_p2 = ($signed(e_26_fu_293_p3) + $signed(6'd63));

assign e_28_fu_326_p3 = ((tmp_152_fu_300_p3[0:0] == 1'b1) ? e_26_fu_293_p3 : e_27_fu_320_p2);

assign e_fu_90_p3 = ((tmp_fu_54_p3[0:0] == 1'b1) ? 6'd46 : 6'd45);

assign f32_4_fu_356_p3 = ((icmp_ln33_reg_375[0:0] == 1'b1) ? 29'd0 : f32_fu_346_p4);

assign f32_fu_346_p4 = {{{e_28_fu_326_p3}, {select_ln39_fu_338_p3}}, {14'd0}};

assign icmp_ln33_fu_48_p2 = ((h == 8'd0) ? 1'b1 : 1'b0);

assign m_15_fu_122_p2 = m_reg_380 << 10'd1;

assign m_16_fu_127_p3 = ((tmp_146_reg_386[0:0] == 1'b1) ? m_reg_380 : m_15_fu_122_p2);

assign m_17_fu_141_p2 = m_16_fu_127_p3 << 10'd1;

assign m_18_fu_152_p3 = ((tmp_147_fu_133_p3[0:0] == 1'b1) ? m_16_fu_127_p3 : m_17_fu_141_p2);

assign m_19_fu_175_p2 = m_18_fu_152_p3 << 10'd1;

assign m_20_fu_187_p3 = ((tmp_148_fu_167_p3[0:0] == 1'b1) ? m_18_fu_152_p3 : m_19_fu_175_p2);

assign m_21_fu_211_p2 = m_20_reg_397 << 10'd1;

assign m_22_fu_221_p3 = ((tmp_149_reg_409[0:0] == 1'b1) ? m_20_reg_397 : m_21_fu_211_p2);

assign m_23_fu_255_p2 = m_22_reg_415 << 10'd1;

assign m_24_fu_260_p3 = ((tmp_150_reg_421[0:0] == 1'b1) ? m_22_reg_415 : m_23_fu_255_p2);

assign m_25_fu_274_p2 = m_24_fu_260_p3 << 10'd1;

assign m_26_fu_285_p3 = ((tmp_151_fu_266_p3[0:0] == 1'b1) ? m_24_fu_260_p3 : m_25_fu_274_p2);

assign m_27_fu_312_p3 = {{trunc_ln39_2_fu_308_p1}, {1'd0}};

assign m_fu_82_p3 = ((tmp_fu_54_p3[0:0] == 1'b1) ? st_fu_62_p3 : sf_fu_74_p3);

assign select_ln39_fu_338_p3 = ((tmp_152_fu_300_p3[0:0] == 1'b1) ? trunc_ln41_fu_334_p1 : m_27_fu_312_p3);

assign sext_ln32_fu_363_p1 = $signed(f32_4_fu_356_p3);

assign sf_fu_74_p3 = {{trunc_ln39_fu_70_p1}, {3'd0}};

assign st_fu_62_p3 = {{h}, {2'd0}};

assign tmp_146_fu_98_p3 = m_fu_82_p3[32'd9];

assign tmp_147_fu_133_p3 = m_16_fu_127_p3[32'd9];

assign tmp_148_fu_167_p3 = m_18_fu_152_p3[32'd9];

assign tmp_150_fu_233_p3 = m_22_fu_221_p3[32'd9];

assign tmp_151_fu_266_p3 = m_24_fu_260_p3[32'd9];

assign tmp_152_fu_300_p3 = m_26_fu_285_p3[32'd9];

assign tmp_fu_54_p3 = h[32'd7];

assign trunc_ln39_2_fu_308_p1 = m_26_fu_285_p3[7:0];

assign trunc_ln39_fu_70_p1 = h[6:0];

assign trunc_ln41_fu_334_p1 = m_26_fu_285_p3[8:0];

assign zext_ln32_fu_367_p1 = $unsigned(sext_ln32_fu_363_p1);

always @ (posedge ap_clk) begin
    m_reg_380[1:0] <= 2'b00;
    e_16_reg_391[5:2] <= 4'b1011;
end

endmodule //swiglu_fp16_to_fp32
