-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_fp16_to_fp32 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    h : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of swiglu_fp16_to_fp32 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv31_38000000 : STD_LOGIC_VECTOR (30 downto 0) := "0111000000000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";

attribute shreg_extract : string;
    signal mant_fu_92_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mant_reg_639 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal mant_reg_639_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal mant_reg_639_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_688_reg_645 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_688_reg_645_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_688_reg_645_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_fu_104_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_reg_653 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_reg_653_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_reg_653_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln41_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_660 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_660_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_660_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_5_fu_242_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_5_reg_666 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_4_fu_250_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_4_reg_672 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_692_reg_677 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_5_fu_266_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_5_reg_683 : STD_LOGIC_VECTOR (5 downto 0);
    signal m_9_fu_308_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_9_reg_688 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_694_fu_324_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_694_reg_694 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_10_fu_338_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_10_reg_699 : STD_LOGIC_VECTOR (5 downto 0);
    signal m_13_fu_376_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_13_reg_705 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_696_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_696_reg_711 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_14_fu_405_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_14_reg_716 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln41_fu_114_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_124_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln41_fu_118_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln_fu_134_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln47_fu_156_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_689_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_160_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_1_fu_168_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_690_fu_184_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_2_fu_192_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_fu_176_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_1_fu_198_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal m_3_fu_206_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_2_fu_214_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_691_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_4_fu_230_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_3_fu_236_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m_6_fu_272_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_7_fu_277_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_6_fu_283_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_693_fu_288_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_8_fu_296_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_7_fu_302_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_8_fu_316_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_9_fu_332_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m_10_fu_346_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_11_fu_351_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_695_fu_357_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_12_fu_365_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_11_fu_371_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_12_fu_384_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_13_fu_399_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln53_1_fu_420_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln53_fu_427_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln53_fu_431_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_188_fu_437_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_14_fu_457_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_15_fu_462_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_697_fu_468_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_16_fu_476_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal e_15_fu_482_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m_17_fu_487_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln47_1_fu_510_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal e_16_fu_495_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_698_fu_502_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln49_fu_528_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal m_18_fu_514_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal e_17_fu_522_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln44_fu_540_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln49_fu_548_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln47_fu_532_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln43_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_1_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_1_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal f32_4_fu_611_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_4_fu_611_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_4_fu_611_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_4_fu_611_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_4_fu_611_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_4_fu_611_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal f32_4_fu_611_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln55_fu_635_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal h_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_4_fu_611_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal f32_4_fu_611_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal f32_4_fu_611_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal f32_4_fu_611_p7 : STD_LOGIC_VECTOR (2 downto 0);

    component swiglu_sparsemux_9_3_32_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    sparsemux_9_3_32_1_0_U751 : component swiglu_sparsemux_9_3_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 32,
        CASE1 => "010",
        din1_WIDTH => 32,
        CASE2 => "001",
        din2_WIDTH => 32,
        CASE3 => "000",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => f32_4_fu_611_p2,
        din1 => f32_4_fu_611_p4,
        din2 => f32_4_fu_611_p6,
        din3 => f32_4_fu_611_p8,
        def => f32_4_fu_611_p9,
        sel => f32_4_fu_611_p10,
        dout => f32_4_fu_611_p11);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= bitcast_ln55_fu_635_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                e_10_reg_699 <= e_10_fu_338_p3;
                e_14_reg_716 <= e_14_fu_405_p3;
                e_4_reg_672 <= e_4_fu_250_p3;
                e_5_reg_683 <= e_5_fu_266_p2;
                exp_reg_653 <= h_int_reg(14 downto 10);
                exp_reg_653_pp0_iter1_reg <= exp_reg_653;
                exp_reg_653_pp0_iter2_reg <= exp_reg_653_pp0_iter1_reg;
                icmp_ln41_reg_660 <= icmp_ln41_fu_142_p2;
                icmp_ln41_reg_660_pp0_iter1_reg <= icmp_ln41_reg_660;
                icmp_ln41_reg_660_pp0_iter2_reg <= icmp_ln41_reg_660_pp0_iter1_reg;
                m_13_reg_705 <= m_13_fu_376_p3;
                m_5_reg_666 <= m_5_fu_242_p3;
                m_9_reg_688 <= m_9_fu_308_p3;
                mant_reg_639 <= mant_fu_92_p1;
                mant_reg_639_pp0_iter1_reg <= mant_reg_639;
                mant_reg_639_pp0_iter2_reg <= mant_reg_639_pp0_iter1_reg;
                tmp_688_reg_645 <= h_int_reg(15 downto 15);
                tmp_688_reg_645_pp0_iter1_reg <= tmp_688_reg_645;
                tmp_688_reg_645_pp0_iter2_reg <= tmp_688_reg_645_pp0_iter1_reg;
                tmp_692_reg_677 <= m_5_fu_242_p3(9 downto 9);
                tmp_694_reg_694 <= m_9_fu_308_p3(9 downto 9);
                tmp_696_reg_711 <= m_13_fu_376_p3(9 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                h_int_reg <= h;
            end if;
        end if;
    end process;
    add_ln53_fu_431_p2 <= std_logic_vector(unsigned(zext_ln53_fu_427_p1) + unsigned(ap_const_lv31_38000000));
    and_ln43_1_fu_596_p2 <= (xor_ln41_fu_580_p2 and icmp_ln43_1_fu_591_p2);
    and_ln43_fu_585_p2 <= (xor_ln41_fu_580_p2 and icmp_ln43_fu_575_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(bitcast_ln55_fu_635_p1, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= bitcast_ln55_fu_635_p1;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bitcast_ln55_fu_635_p1 <= f32_4_fu_611_p11;
    e_10_fu_338_p3 <= 
        e_8_fu_316_p3 when (tmp_694_fu_324_p3(0) = '1') else 
        e_9_fu_332_p2;
    e_11_fu_371_p2 <= std_logic_vector(unsigned(e_10_reg_699) + unsigned(ap_const_lv6_3F));
    e_12_fu_384_p3 <= 
        e_10_reg_699 when (tmp_695_fu_357_p3(0) = '1') else 
        e_11_fu_371_p2;
    e_13_fu_399_p2 <= std_logic_vector(unsigned(e_12_fu_384_p3) + unsigned(ap_const_lv6_3F));
    e_14_fu_405_p3 <= 
        e_12_fu_384_p3 when (tmp_696_fu_391_p3(0) = '1') else 
        e_13_fu_399_p2;
    e_15_fu_482_p2 <= std_logic_vector(unsigned(e_14_reg_716) + unsigned(ap_const_lv6_3F));
    e_16_fu_495_p3 <= 
        e_14_reg_716 when (tmp_697_fu_468_p3(0) = '1') else 
        e_15_fu_482_p2;
    e_17_fu_522_p2 <= std_logic_vector(unsigned(e_16_fu_495_p3) + unsigned(ap_const_lv6_3F));
    e_1_fu_198_p3 <= 
        ap_const_lv6_2F when (tmp_689_fu_148_p3(0) = '1') else 
        ap_const_lv6_2E;
    e_2_fu_214_p3 <= 
        e_fu_176_p3 when (tmp_690_fu_184_p3(0) = '1') else 
        e_1_fu_198_p3;
    e_3_fu_236_p2 <= std_logic_vector(unsigned(e_2_fu_214_p3) + unsigned(ap_const_lv6_3F));
    e_4_fu_250_p3 <= 
        e_2_fu_214_p3 when (tmp_691_fu_222_p3(0) = '1') else 
        e_3_fu_236_p2;
    e_5_fu_266_p2 <= std_logic_vector(unsigned(e_4_fu_250_p3) + unsigned(ap_const_lv6_3F));
    e_6_fu_283_p3 <= 
        e_4_reg_672 when (tmp_692_reg_677(0) = '1') else 
        e_5_reg_683;
    e_7_fu_302_p2 <= std_logic_vector(unsigned(e_6_fu_283_p3) + unsigned(ap_const_lv6_3F));
    e_8_fu_316_p3 <= 
        e_6_fu_283_p3 when (tmp_693_fu_288_p3(0) = '1') else 
        e_7_fu_302_p2;
    e_9_fu_332_p2 <= std_logic_vector(unsigned(e_8_fu_316_p3) + unsigned(ap_const_lv6_3F));
    e_fu_176_p3 <= 
        ap_const_lv6_30 when (tmp_689_fu_148_p3(0) = '1') else 
        ap_const_lv6_2F;
    exp_fu_104_p4 <= h_int_reg(14 downto 10);
    f32_4_fu_611_p10 <= ((icmp_ln41_reg_660_pp0_iter2_reg & and_ln43_fu_585_p2) & and_ln43_1_fu_596_p2);
    f32_4_fu_611_p2 <= (tmp_688_reg_645_pp0_iter2_reg & ap_const_lv31_0);
    f32_4_fu_611_p4 <= ((((tmp_688_reg_645_pp0_iter2_reg & ap_const_lv1_0) & sext_ln49_fu_548_p1) & select_ln47_fu_532_p3) & ap_const_lv14_0);
    f32_4_fu_611_p6 <= (((tmp_688_reg_645_pp0_iter2_reg & ap_const_lv8_FF) & mant_reg_639_pp0_iter2_reg) & ap_const_lv13_0);
    f32_4_fu_611_p8 <= (((tmp_688_reg_645_pp0_iter2_reg & tmp_188_fu_437_p4) & mant_reg_639_pp0_iter2_reg) & ap_const_lv13_0);
    f32_4_fu_611_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    icmp_ln41_fu_142_p2 <= "1" when (or_ln_fu_134_p3 = ap_const_lv10_0) else "0";
    icmp_ln43_1_fu_591_p2 <= "1" when (exp_reg_653_pp0_iter2_reg = ap_const_lv5_1F) else "0";
    icmp_ln43_fu_575_p2 <= "1" when (exp_reg_653_pp0_iter2_reg = ap_const_lv5_0) else "0";
    m_10_fu_346_p2 <= std_logic_vector(shift_left(unsigned(m_9_reg_688),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_11_fu_351_p3 <= 
        m_9_reg_688 when (tmp_694_reg_694(0) = '1') else 
        m_10_fu_346_p2;
    m_12_fu_365_p2 <= std_logic_vector(shift_left(unsigned(m_11_fu_351_p3),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_13_fu_376_p3 <= 
        m_11_fu_351_p3 when (tmp_695_fu_357_p3(0) = '1') else 
        m_12_fu_365_p2;
    m_14_fu_457_p2 <= std_logic_vector(shift_left(unsigned(m_13_reg_705),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_15_fu_462_p3 <= 
        m_13_reg_705 when (tmp_696_reg_711(0) = '1') else 
        m_14_fu_457_p2;
    m_16_fu_476_p2 <= std_logic_vector(shift_left(unsigned(m_15_fu_462_p3),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_17_fu_487_p3 <= 
        m_15_fu_462_p3 when (tmp_697_fu_468_p3(0) = '1') else 
        m_16_fu_476_p2;
    m_18_fu_514_p3 <= (trunc_ln47_1_fu_510_p1 & ap_const_lv1_0);
    m_1_fu_168_p3 <= 
        mant_fu_92_p1 when (tmp_689_fu_148_p3(0) = '1') else 
        shl_ln_fu_160_p3;
    m_2_fu_192_p2 <= std_logic_vector(shift_left(unsigned(m_1_fu_168_p3),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_3_fu_206_p3 <= 
        m_1_fu_168_p3 when (tmp_690_fu_184_p3(0) = '1') else 
        m_2_fu_192_p2;
    m_4_fu_230_p2 <= std_logic_vector(shift_left(unsigned(m_3_fu_206_p3),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_5_fu_242_p3 <= 
        m_3_fu_206_p3 when (tmp_691_fu_222_p3(0) = '1') else 
        m_4_fu_230_p2;
    m_6_fu_272_p2 <= std_logic_vector(shift_left(unsigned(m_5_reg_666),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_7_fu_277_p3 <= 
        m_5_reg_666 when (tmp_692_reg_677(0) = '1') else 
        m_6_fu_272_p2;
    m_8_fu_296_p2 <= std_logic_vector(shift_left(unsigned(m_7_fu_277_p3),to_integer(unsigned('0' & ap_const_lv10_1(10-1 downto 0)))));
    m_9_fu_308_p3 <= 
        m_7_fu_277_p3 when (tmp_693_fu_288_p3(0) = '1') else 
        m_8_fu_296_p2;
    mant_fu_92_p1 <= h_int_reg(10 - 1 downto 0);
    or_ln41_fu_118_p2 <= (trunc_ln41_fu_114_p1 or exp_fu_104_p4);
    or_ln_fu_134_p3 <= (tmp_fu_124_p4 & or_ln41_fu_118_p2);
    select_ln44_fu_540_p3 <= 
        e_16_fu_495_p3 when (tmp_698_fu_502_p3(0) = '1') else 
        e_17_fu_522_p2;
    select_ln47_fu_532_p3 <= 
        trunc_ln49_fu_528_p1 when (tmp_698_fu_502_p3(0) = '1') else 
        m_18_fu_514_p3;
        sext_ln49_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln44_fu_540_p3),7));

    shl_ln53_1_fu_420_p3 <= (exp_reg_653_pp0_iter2_reg & ap_const_lv23_0);
    shl_ln_fu_160_p3 <= (trunc_ln47_fu_156_p1 & ap_const_lv1_0);
    tmp_188_fu_437_p4 <= add_ln53_fu_431_p2(30 downto 23);
    tmp_689_fu_148_p3 <= h_int_reg(9 downto 9);
    tmp_690_fu_184_p3 <= m_1_fu_168_p3(9 downto 9);
    tmp_691_fu_222_p3 <= m_3_fu_206_p3(9 downto 9);
    tmp_693_fu_288_p3 <= m_7_fu_277_p3(9 downto 9);
    tmp_694_fu_324_p3 <= m_9_fu_308_p3(9 downto 9);
    tmp_695_fu_357_p3 <= m_11_fu_351_p3(9 downto 9);
    tmp_696_fu_391_p3 <= m_13_fu_376_p3(9 downto 9);
    tmp_697_fu_468_p3 <= m_15_fu_462_p3(9 downto 9);
    tmp_698_fu_502_p3 <= m_17_fu_487_p3(9 downto 9);
    tmp_fu_124_p4 <= h_int_reg(9 downto 5);
    trunc_ln41_fu_114_p1 <= h_int_reg(5 - 1 downto 0);
    trunc_ln47_1_fu_510_p1 <= m_17_fu_487_p3(8 - 1 downto 0);
    trunc_ln47_fu_156_p1 <= h_int_reg(9 - 1 downto 0);
    trunc_ln49_fu_528_p1 <= m_17_fu_487_p3(9 - 1 downto 0);
    xor_ln41_fu_580_p2 <= (icmp_ln41_reg_660_pp0_iter2_reg xor ap_const_lv1_1);
    zext_ln53_fu_427_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln53_1_fu_420_p3),31));
end behav;
