-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_mac_blocks_down_q6k5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ql_buf_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_0_ce0 : OUT STD_LOGIC;
    ql_buf_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_1_ce0 : OUT STD_LOGIC;
    ql_buf_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_2_ce0 : OUT STD_LOGIC;
    ql_buf_2_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_3_ce0 : OUT STD_LOGIC;
    ql_buf_3_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_4_ce0 : OUT STD_LOGIC;
    ql_buf_4_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_5_ce0 : OUT STD_LOGIC;
    ql_buf_5_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_6_ce0 : OUT STD_LOGIC;
    ql_buf_6_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ql_buf_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ql_buf_7_ce0 : OUT STD_LOGIC;
    ql_buf_7_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_0_ce0 : OUT STD_LOGIC;
    qh_buf_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_1_ce0 : OUT STD_LOGIC;
    qh_buf_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_2_ce0 : OUT STD_LOGIC;
    qh_buf_2_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_3_ce0 : OUT STD_LOGIC;
    qh_buf_3_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_4_ce0 : OUT STD_LOGIC;
    qh_buf_4_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_5_ce0 : OUT STD_LOGIC;
    qh_buf_5_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_6_ce0 : OUT STD_LOGIC;
    qh_buf_6_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    qh_buf_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qh_buf_7_ce0 : OUT STD_LOGIC;
    qh_buf_7_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_0_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_1_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_2_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_3_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_4_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_5_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_6_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_7_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_8_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_9_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_10_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_11_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_12_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_13_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_14_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_15_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_16_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_17_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_18_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_19_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_20_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_21_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_22_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_23_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_24_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_25_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_26_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_27_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_28_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_29_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_30_val : IN STD_LOGIC_VECTOR (127 downto 0);
    sc_buf_31_val : IN STD_LOGIC_VECTOR (127 downto 0);
    d_buf_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_17_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_18_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_19_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_20_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_21_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_22_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_23_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_24_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_25_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_27_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_28_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_29_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_30_val : IN STD_LOGIC_VECTOR (31 downto 0);
    d_buf_31_val : IN STD_LOGIC_VECTOR (31 downto 0);
    gate_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_0_ce0 : OUT STD_LOGIC;
    gate_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_1_ce0 : OUT STD_LOGIC;
    gate_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_2_ce0 : OUT STD_LOGIC;
    gate_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_3_ce0 : OUT STD_LOGIC;
    gate_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_4_ce0 : OUT STD_LOGIC;
    gate_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_5_ce0 : OUT STD_LOGIC;
    gate_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_6_ce0 : OUT STD_LOGIC;
    gate_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    gate_7_ce0 : OUT STD_LOGIC;
    gate_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gate_scale : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of swiglu_mac_blocks_down_q6k5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv56_0 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv7_68 : STD_LOGIC_VECTOR (6 downto 0) := "1101000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv56_FFFFFFFFFFFFFF : STD_LOGIC_VECTOR (55 downto 0) := "11111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv7_26 : STD_LOGIC_VECTOR (6 downto 0) := "0100110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln576_fu_1038_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln576_reg_2205 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln576_1_fu_1043_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln576_1_reg_2210 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_87_fu_1047_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_87_reg_2215 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_88_fu_1058_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_88_reg_2220 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_1067_p19 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_reg_2225 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_s_fu_1100_p19 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_s_reg_2230 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_65_fu_1133_p19 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_65_reg_2235 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_66_fu_1166_p19 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_66_reg_2240 : STD_LOGIC_VECTOR (127 downto 0);
    signal icmp_ln624_fu_1214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln624_reg_2245 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_171_fu_1220_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_171_reg_2250 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln624_fu_1234_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal select_ln624_reg_2255 : STD_LOGIC_VECTOR (55 downto 0);
    signal add_i_i14_lcssa_phi_load_reg_2264 : STD_LOGIC_VECTOR (88 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_90_fu_1374_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_90_reg_2368 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln624_1_fu_1416_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln624_1_reg_2373 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sub_ln624_1_fu_1420_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln624_1_reg_2378 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln624_4_fu_1426_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln624_4_reg_2385 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln624_fu_1514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln624_reg_2390 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal icmp_ln624_3_fu_1520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln624_3_reg_2395 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln624_fu_1539_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal lshr_ln624_reg_2400 : STD_LOGIC_VECTOR (55 downto 0);
    signal shl_ln624_fu_1557_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal shl_ln624_reg_2405 : STD_LOGIC_VECTOR (55 downto 0);
    signal retval_0_i_i_fu_1652_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_0_i_i_reg_2410 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_done : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_idle : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_ready : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_0_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_1_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_2_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_3_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_4_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_5_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_6_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_6_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_7_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_7_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_0_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_1_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_2_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_3_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_4_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_4_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_5_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_5_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_6_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_6_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_7_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_7_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_0_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_1_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_2_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_3_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_4_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_5_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_6_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_7_ce0 : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_1_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_1_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_2_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_2_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_3_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_3_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_4_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_4_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_5_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_5_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_6_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_6_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_7_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_7_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_8_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_8_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_9_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_9_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_10_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_10_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_11_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_11_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_12_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_12_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_13_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_13_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_14_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_14_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_15_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_15_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_16_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_16_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_17_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_17_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_18_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_18_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_19_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_19_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_20_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_20_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_21_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_21_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_22_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_22_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_23_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_23_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_24_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_24_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_25_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_25_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_26_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_26_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_27_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_27_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_28_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_28_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_29_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_29_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_30_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_30_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_31_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_31_load_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_done : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_idle : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_ready : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_add_i_i14_phi_out : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_add_i_i14_phi_out_ap_vld : STD_LOGIC;
    signal grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln576_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_i_i14_lcssa_phi_fu_308 : STD_LOGIC_VECTOR (88 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal total_fu_312 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000000";
    signal g_fu_316 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln576_fu_1032_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_fu_1067_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_s_fu_1100_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_65_fu_1133_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_66_fu_1166_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal trunc_ln_fu_1204_p4 : STD_LOGIC_VECTOR (55 downto 0);
    signal sub_ln624_fu_1228_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal tmp_67_fu_1405_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal trunc_ln624_fu_1412_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln624_fu_1432_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln624_fu_1435_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_172_fu_1445_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln624_1_fu_1461_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal lshr_ln624_2_fu_1464_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal and_ln624_fu_1470_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal icmp_ln624_1_fu_1455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln624_2_fu_1475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_173_fu_1487_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_174_fu_1501_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1501_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln624_fu_1495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln624_1_fu_1508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln624_fu_1481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln624_1_fu_1526_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln624_fu_1531_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln624_2_fu_1535_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal sub_ln624_2_fu_1544_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln624_1_fu_1549_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln624_6_fu_1553_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal cond49_i_i_in_fu_1562_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal zext_ln624_3_fu_1567_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal zext_ln624_4_fu_1571_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln624_2_fu_1574_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal lshr_ln624_1_fu_1580_p4 : STD_LOGIC_VECTOR (55 downto 0);
    signal tmp_175_fu_1594_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln624_3_fu_1610_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln624_1_fu_1602_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln624_2_fu_1615_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln624_3_fu_1619_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln624_5_fu_1590_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_75_fu_1625_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_fu_1632_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_fu_1644_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln777_fu_1648_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1005_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal tmp_fu_1067_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_1067_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_1100_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_65_fu_1133_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_66_fu_1166_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_67_fu_1405_p0 : STD_LOGIC_VECTOR (55 downto 0);
    signal tmp_67_fu_1405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_174_fu_1501_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln607 : IN STD_LOGIC_VECTOR (9 downto 0);
        gate_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_0_ce0 : OUT STD_LOGIC;
        gate_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_1_ce0 : OUT STD_LOGIC;
        gate_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_2_ce0 : OUT STD_LOGIC;
        gate_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_3_ce0 : OUT STD_LOGIC;
        gate_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_4_ce0 : OUT STD_LOGIC;
        gate_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_5_ce0 : OUT STD_LOGIC;
        gate_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_6_ce0 : OUT STD_LOGIC;
        gate_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        gate_7_ce0 : OUT STD_LOGIC;
        gate_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp_87 : IN STD_LOGIC_VECTOR (1 downto 0);
        ql_buf_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_0_ce0 : OUT STD_LOGIC;
        ql_buf_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_1_ce0 : OUT STD_LOGIC;
        ql_buf_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_2_ce0 : OUT STD_LOGIC;
        ql_buf_2_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_3_ce0 : OUT STD_LOGIC;
        ql_buf_3_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_4_ce0 : OUT STD_LOGIC;
        ql_buf_4_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_5_ce0 : OUT STD_LOGIC;
        ql_buf_5_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_6_ce0 : OUT STD_LOGIC;
        ql_buf_6_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ql_buf_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ql_buf_7_ce0 : OUT STD_LOGIC;
        ql_buf_7_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_0_ce0 : OUT STD_LOGIC;
        qh_buf_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_1_ce0 : OUT STD_LOGIC;
        qh_buf_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_2_ce0 : OUT STD_LOGIC;
        qh_buf_2_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_3_ce0 : OUT STD_LOGIC;
        qh_buf_3_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_4_ce0 : OUT STD_LOGIC;
        qh_buf_4_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_5_ce0 : OUT STD_LOGIC;
        qh_buf_5_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_6_ce0 : OUT STD_LOGIC;
        qh_buf_6_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        qh_buf_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        qh_buf_7_ce0 : OUT STD_LOGIC;
        qh_buf_7_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        tmp : IN STD_LOGIC_VECTOR (127 downto 0);
        tmp_s : IN STD_LOGIC_VECTOR (127 downto 0);
        tmp_65 : IN STD_LOGIC_VECTOR (127 downto 0);
        tmp_66 : IN STD_LOGIC_VECTOR (127 downto 0);
        acc_local_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_1_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_1_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_2_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_2_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_3_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_3_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_4_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_4_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_5_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_5_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_6_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_6_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_7_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_7_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_8_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_8_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_9_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_9_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_10_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_10_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_11_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_11_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_12_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_12_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_13_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_13_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_14_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_14_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_15_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_15_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_16_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_16_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_17_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_17_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_18_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_18_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_19_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_19_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_20_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_20_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_21_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_21_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_22_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_22_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_23_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_23_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_24_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_24_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_25_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_25_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_26_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_26_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_27_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_27_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_28_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_28_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_29_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_29_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_30_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_30_load_out_ap_vld : OUT STD_LOGIC;
        acc_local_31_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_local_31_load_out_ap_vld : OUT STD_LOGIC );
    end component;


    component swiglu_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        total : IN STD_LOGIC_VECTOR (55 downto 0);
        add_i_i14_lcssa_phi : IN STD_LOGIC_VECTOR (88 downto 0);
        tmp_90 : IN STD_LOGIC_VECTOR (4 downto 0);
        acc_local_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_8_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_16_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_24_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_1_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_9_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_17_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_25_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_2_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_10_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_18_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_26_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_3_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_11_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_19_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_27_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_4_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_12_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_20_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_28_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_5_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_13_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_21_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_29_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_6_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_14_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_22_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_30_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_7_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_15_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_23_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_local_31_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_17_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_18_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_19_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_20_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_21_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_22_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_23_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_24_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_25_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_27_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_28_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_29_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_30_val : IN STD_LOGIC_VECTOR (31 downto 0);
        d_buf_31_val : IN STD_LOGIC_VECTOR (31 downto 0);
        add_i_i14_phi_out : OUT STD_LOGIC_VECTOR (88 downto 0);
        add_i_i14_phi_out_ap_vld : OUT STD_LOGIC );
    end component;


    component swiglu_fmul_32ns_32ns_32_7_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_sparsemux_17_3_128_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (127 downto 0);
        din1 : IN STD_LOGIC_VECTOR (127 downto 0);
        din2 : IN STD_LOGIC_VECTOR (127 downto 0);
        din3 : IN STD_LOGIC_VECTOR (127 downto 0);
        din4 : IN STD_LOGIC_VECTOR (127 downto 0);
        din5 : IN STD_LOGIC_VECTOR (127 downto 0);
        din6 : IN STD_LOGIC_VECTOR (127 downto 0);
        din7 : IN STD_LOGIC_VECTOR (127 downto 0);
        def : IN STD_LOGIC_VECTOR (127 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component swiglu_ctlz_56_56_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (55 downto 0);
        dout : OUT STD_LOGIC_VECTOR (55 downto 0) );
    end component;


    component swiglu_bitselect_1ns_56ns_6ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (55 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842 : component swiglu_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start,
        ap_done => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_done,
        ap_idle => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_idle,
        ap_ready => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_ready,
        zext_ln607 => tmp_88_reg_2220,
        gate_0_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_0_address0,
        gate_0_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_0_ce0,
        gate_0_q0 => gate_0_q0,
        gate_1_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_1_address0,
        gate_1_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_1_ce0,
        gate_1_q0 => gate_1_q0,
        gate_2_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_2_address0,
        gate_2_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_2_ce0,
        gate_2_q0 => gate_2_q0,
        gate_3_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_3_address0,
        gate_3_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_3_ce0,
        gate_3_q0 => gate_3_q0,
        gate_4_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_4_address0,
        gate_4_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_4_ce0,
        gate_4_q0 => gate_4_q0,
        gate_5_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_5_address0,
        gate_5_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_5_ce0,
        gate_5_q0 => gate_5_q0,
        gate_6_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_6_address0,
        gate_6_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_6_ce0,
        gate_6_q0 => gate_6_q0,
        gate_7_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_7_address0,
        gate_7_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_7_ce0,
        gate_7_q0 => gate_7_q0,
        tmp_87 => tmp_87_reg_2215,
        ql_buf_0_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_0_address0,
        ql_buf_0_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_0_ce0,
        ql_buf_0_q0 => ql_buf_0_q0,
        ql_buf_1_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_1_address0,
        ql_buf_1_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_1_ce0,
        ql_buf_1_q0 => ql_buf_1_q0,
        ql_buf_2_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_2_address0,
        ql_buf_2_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_2_ce0,
        ql_buf_2_q0 => ql_buf_2_q0,
        ql_buf_3_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_3_address0,
        ql_buf_3_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_3_ce0,
        ql_buf_3_q0 => ql_buf_3_q0,
        ql_buf_4_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_4_address0,
        ql_buf_4_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_4_ce0,
        ql_buf_4_q0 => ql_buf_4_q0,
        ql_buf_5_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_5_address0,
        ql_buf_5_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_5_ce0,
        ql_buf_5_q0 => ql_buf_5_q0,
        ql_buf_6_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_6_address0,
        ql_buf_6_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_6_ce0,
        ql_buf_6_q0 => ql_buf_6_q0,
        ql_buf_7_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_7_address0,
        ql_buf_7_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_7_ce0,
        ql_buf_7_q0 => ql_buf_7_q0,
        qh_buf_0_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_0_address0,
        qh_buf_0_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_0_ce0,
        qh_buf_0_q0 => qh_buf_0_q0,
        qh_buf_1_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_1_address0,
        qh_buf_1_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_1_ce0,
        qh_buf_1_q0 => qh_buf_1_q0,
        qh_buf_2_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_2_address0,
        qh_buf_2_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_2_ce0,
        qh_buf_2_q0 => qh_buf_2_q0,
        qh_buf_3_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_3_address0,
        qh_buf_3_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_3_ce0,
        qh_buf_3_q0 => qh_buf_3_q0,
        qh_buf_4_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_4_address0,
        qh_buf_4_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_4_ce0,
        qh_buf_4_q0 => qh_buf_4_q0,
        qh_buf_5_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_5_address0,
        qh_buf_5_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_5_ce0,
        qh_buf_5_q0 => qh_buf_5_q0,
        qh_buf_6_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_6_address0,
        qh_buf_6_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_6_ce0,
        qh_buf_6_q0 => qh_buf_6_q0,
        qh_buf_7_address0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_7_address0,
        qh_buf_7_ce0 => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_7_ce0,
        qh_buf_7_q0 => qh_buf_7_q0,
        empty => trunc_ln576_reg_2205,
        tmp => tmp_reg_2225,
        tmp_s => tmp_s_reg_2230,
        tmp_65 => tmp_65_reg_2235,
        tmp_66 => tmp_66_reg_2240,
        acc_local_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_load_out,
        acc_local_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_load_out_ap_vld,
        acc_local_1_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_1_load_out,
        acc_local_1_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_1_load_out_ap_vld,
        acc_local_2_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_2_load_out,
        acc_local_2_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_2_load_out_ap_vld,
        acc_local_3_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_3_load_out,
        acc_local_3_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_3_load_out_ap_vld,
        acc_local_4_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_4_load_out,
        acc_local_4_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_4_load_out_ap_vld,
        acc_local_5_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_5_load_out,
        acc_local_5_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_5_load_out_ap_vld,
        acc_local_6_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_6_load_out,
        acc_local_6_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_6_load_out_ap_vld,
        acc_local_7_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_7_load_out,
        acc_local_7_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_7_load_out_ap_vld,
        acc_local_8_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_8_load_out,
        acc_local_8_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_8_load_out_ap_vld,
        acc_local_9_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_9_load_out,
        acc_local_9_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_9_load_out_ap_vld,
        acc_local_10_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_10_load_out,
        acc_local_10_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_10_load_out_ap_vld,
        acc_local_11_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_11_load_out,
        acc_local_11_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_11_load_out_ap_vld,
        acc_local_12_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_12_load_out,
        acc_local_12_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_12_load_out_ap_vld,
        acc_local_13_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_13_load_out,
        acc_local_13_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_13_load_out_ap_vld,
        acc_local_14_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_14_load_out,
        acc_local_14_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_14_load_out_ap_vld,
        acc_local_15_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_15_load_out,
        acc_local_15_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_15_load_out_ap_vld,
        acc_local_16_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_16_load_out,
        acc_local_16_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_16_load_out_ap_vld,
        acc_local_17_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_17_load_out,
        acc_local_17_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_17_load_out_ap_vld,
        acc_local_18_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_18_load_out,
        acc_local_18_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_18_load_out_ap_vld,
        acc_local_19_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_19_load_out,
        acc_local_19_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_19_load_out_ap_vld,
        acc_local_20_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_20_load_out,
        acc_local_20_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_20_load_out_ap_vld,
        acc_local_21_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_21_load_out,
        acc_local_21_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_21_load_out_ap_vld,
        acc_local_22_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_22_load_out,
        acc_local_22_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_22_load_out_ap_vld,
        acc_local_23_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_23_load_out,
        acc_local_23_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_23_load_out_ap_vld,
        acc_local_24_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_24_load_out,
        acc_local_24_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_24_load_out_ap_vld,
        acc_local_25_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_25_load_out,
        acc_local_25_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_25_load_out_ap_vld,
        acc_local_26_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_26_load_out,
        acc_local_26_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_26_load_out_ap_vld,
        acc_local_27_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_27_load_out,
        acc_local_27_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_27_load_out_ap_vld,
        acc_local_28_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_28_load_out,
        acc_local_28_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_28_load_out_ap_vld,
        acc_local_29_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_29_load_out,
        acc_local_29_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_29_load_out_ap_vld,
        acc_local_30_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_30_load_out,
        acc_local_30_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_30_load_out_ap_vld,
        acc_local_31_load_out => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_31_load_out,
        acc_local_31_load_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_31_load_out_ap_vld);

    grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933 : component swiglu_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start,
        ap_done => grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_done,
        ap_idle => grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_idle,
        ap_ready => grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_ready,
        total => total_fu_312,
        add_i_i14_lcssa_phi => add_i_i14_lcssa_phi_load_reg_2264,
        tmp_90 => tmp_90_reg_2368,
        acc_local_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_load_out,
        acc_local_8_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_8_load_out,
        acc_local_16_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_16_load_out,
        acc_local_24_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_24_load_out,
        acc_local_1_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_1_load_out,
        acc_local_9_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_9_load_out,
        acc_local_17_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_17_load_out,
        acc_local_25_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_25_load_out,
        acc_local_2_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_2_load_out,
        acc_local_10_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_10_load_out,
        acc_local_18_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_18_load_out,
        acc_local_26_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_26_load_out,
        acc_local_3_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_3_load_out,
        acc_local_11_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_11_load_out,
        acc_local_19_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_19_load_out,
        acc_local_27_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_27_load_out,
        acc_local_4_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_4_load_out,
        acc_local_12_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_12_load_out,
        acc_local_20_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_20_load_out,
        acc_local_28_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_28_load_out,
        acc_local_5_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_5_load_out,
        acc_local_13_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_13_load_out,
        acc_local_21_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_21_load_out,
        acc_local_29_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_29_load_out,
        acc_local_6_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_6_load_out,
        acc_local_14_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_14_load_out,
        acc_local_22_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_22_load_out,
        acc_local_30_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_30_load_out,
        acc_local_7_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_7_load_out,
        acc_local_15_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_15_load_out,
        acc_local_23_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_23_load_out,
        acc_local_31_load_reload => grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_acc_local_31_load_out,
        d_buf_0_val => d_buf_0_val,
        d_buf_1_val => d_buf_1_val,
        d_buf_2_val => d_buf_2_val,
        d_buf_3_val => d_buf_3_val,
        d_buf_4_val => d_buf_4_val,
        d_buf_5_val => d_buf_5_val,
        d_buf_6_val => d_buf_6_val,
        d_buf_7_val => d_buf_7_val,
        d_buf_8_val => d_buf_8_val,
        d_buf_9_val => d_buf_9_val,
        d_buf_10_val => d_buf_10_val,
        d_buf_11_val => d_buf_11_val,
        d_buf_12_val => d_buf_12_val,
        d_buf_13_val => d_buf_13_val,
        d_buf_14_val => d_buf_14_val,
        d_buf_15_val => d_buf_15_val,
        d_buf_16_val => d_buf_16_val,
        d_buf_17_val => d_buf_17_val,
        d_buf_18_val => d_buf_18_val,
        d_buf_19_val => d_buf_19_val,
        d_buf_20_val => d_buf_20_val,
        d_buf_21_val => d_buf_21_val,
        d_buf_22_val => d_buf_22_val,
        d_buf_23_val => d_buf_23_val,
        d_buf_24_val => d_buf_24_val,
        d_buf_25_val => d_buf_25_val,
        d_buf_26_val => d_buf_26_val,
        d_buf_27_val => d_buf_27_val,
        d_buf_28_val => d_buf_28_val,
        d_buf_29_val => d_buf_29_val,
        d_buf_30_val => d_buf_30_val,
        d_buf_31_val => d_buf_31_val,
        add_i_i14_phi_out => grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_add_i_i14_phi_out,
        add_i_i14_phi_out_ap_vld => grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_add_i_i14_phi_out_ap_vld);

    fmul_32ns_32ns_32_7_max_dsp_1_U2249 : component swiglu_fmul_32ns_32ns_32_7_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => retval_0_i_i_reg_2410,
        din1 => gate_scale,
        ce => ap_const_logic_1,
        dout => grp_fu_1005_p2);

    sparsemux_17_3_128_1_1_U2250 : component swiglu_sparsemux_17_3_128_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 128,
        CASE1 => "001",
        din1_WIDTH => 128,
        CASE2 => "010",
        din2_WIDTH => 128,
        CASE3 => "011",
        din3_WIDTH => 128,
        CASE4 => "100",
        din4_WIDTH => 128,
        CASE5 => "101",
        din5_WIDTH => 128,
        CASE6 => "110",
        din6_WIDTH => 128,
        CASE7 => "111",
        din7_WIDTH => 128,
        def_WIDTH => 128,
        sel_WIDTH => 3,
        dout_WIDTH => 128)
    port map (
        din0 => sc_buf_0_val,
        din1 => sc_buf_4_val,
        din2 => sc_buf_8_val,
        din3 => sc_buf_12_val,
        din4 => sc_buf_16_val,
        din5 => sc_buf_20_val,
        din6 => sc_buf_24_val,
        din7 => sc_buf_28_val,
        def => tmp_fu_1067_p17,
        sel => trunc_ln576_1_fu_1043_p1,
        dout => tmp_fu_1067_p19);

    sparsemux_17_3_128_1_1_U2251 : component swiglu_sparsemux_17_3_128_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 128,
        CASE1 => "001",
        din1_WIDTH => 128,
        CASE2 => "010",
        din2_WIDTH => 128,
        CASE3 => "011",
        din3_WIDTH => 128,
        CASE4 => "100",
        din4_WIDTH => 128,
        CASE5 => "101",
        din5_WIDTH => 128,
        CASE6 => "110",
        din6_WIDTH => 128,
        CASE7 => "111",
        din7_WIDTH => 128,
        def_WIDTH => 128,
        sel_WIDTH => 3,
        dout_WIDTH => 128)
    port map (
        din0 => sc_buf_1_val,
        din1 => sc_buf_5_val,
        din2 => sc_buf_9_val,
        din3 => sc_buf_13_val,
        din4 => sc_buf_17_val,
        din5 => sc_buf_21_val,
        din6 => sc_buf_25_val,
        din7 => sc_buf_29_val,
        def => tmp_s_fu_1100_p17,
        sel => trunc_ln576_1_fu_1043_p1,
        dout => tmp_s_fu_1100_p19);

    sparsemux_17_3_128_1_1_U2252 : component swiglu_sparsemux_17_3_128_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 128,
        CASE1 => "001",
        din1_WIDTH => 128,
        CASE2 => "010",
        din2_WIDTH => 128,
        CASE3 => "011",
        din3_WIDTH => 128,
        CASE4 => "100",
        din4_WIDTH => 128,
        CASE5 => "101",
        din5_WIDTH => 128,
        CASE6 => "110",
        din6_WIDTH => 128,
        CASE7 => "111",
        din7_WIDTH => 128,
        def_WIDTH => 128,
        sel_WIDTH => 3,
        dout_WIDTH => 128)
    port map (
        din0 => sc_buf_2_val,
        din1 => sc_buf_6_val,
        din2 => sc_buf_10_val,
        din3 => sc_buf_14_val,
        din4 => sc_buf_18_val,
        din5 => sc_buf_22_val,
        din6 => sc_buf_26_val,
        din7 => sc_buf_30_val,
        def => tmp_65_fu_1133_p17,
        sel => trunc_ln576_1_fu_1043_p1,
        dout => tmp_65_fu_1133_p19);

    sparsemux_17_3_128_1_1_U2253 : component swiglu_sparsemux_17_3_128_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 128,
        CASE1 => "001",
        din1_WIDTH => 128,
        CASE2 => "010",
        din2_WIDTH => 128,
        CASE3 => "011",
        din3_WIDTH => 128,
        CASE4 => "100",
        din4_WIDTH => 128,
        CASE5 => "101",
        din5_WIDTH => 128,
        CASE6 => "110",
        din6_WIDTH => 128,
        CASE7 => "111",
        din7_WIDTH => 128,
        def_WIDTH => 128,
        sel_WIDTH => 3,
        dout_WIDTH => 128)
    port map (
        din0 => sc_buf_3_val,
        din1 => sc_buf_7_val,
        din2 => sc_buf_11_val,
        din3 => sc_buf_15_val,
        din4 => sc_buf_19_val,
        din5 => sc_buf_23_val,
        din6 => sc_buf_27_val,
        din7 => sc_buf_31_val,
        def => tmp_66_fu_1166_p17,
        sel => trunc_ln576_1_fu_1043_p1,
        dout => tmp_66_fu_1166_p19);

    ctlz_56_56_1_1_U2254 : component swiglu_ctlz_56_56_1_1
    generic map (
        din_WIDTH => 56,
        dout_WIDTH => 56)
    port map (
        din => select_ln624_reg_2255,
        dout => tmp_67_fu_1405_p3);

    bitselect_1ns_56ns_6ns_1_1_1_U2255 : component swiglu_bitselect_1ns_56ns_6ns_1_1_1
    generic map (
        DATAWIDTH => 56,
        ADDRWIDTH => 6)
    port map (
        din => select_ln624_reg_2255,
        sel => tmp_174_fu_1501_p2,
        dout => tmp_174_fu_1501_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    ap_return_preg <= grp_fu_1005_p2;
                end if; 
            end if;
        end if;
    end process;


    grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln576_fu_1026_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_ready = ap_const_logic_1)) then 
                    grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_ready = ap_const_logic_1)) then 
                    grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    g_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                g_fu_316 <= ap_const_lv4_0;
            elsif (((icmp_ln576_fu_1026_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                g_fu_316 <= add_ln576_fu_1032_p2;
            end if; 
        end if;
    end process;

    total_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                total_fu_312 <= ap_const_lv56_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                total_fu_312 <= grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_add_i_i14_phi_out(79 downto 24);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_i_i14_lcssa_phi_fu_308 <= grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_add_i_i14_phi_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_i_i14_lcssa_phi_load_reg_2264 <= add_i_i14_lcssa_phi_fu_308;
                    tmp_90_reg_2368(4 downto 2) <= tmp_90_fu_1374_p3(4 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                icmp_ln624_3_reg_2395 <= icmp_ln624_3_fu_1520_p2;
                lshr_ln624_reg_2400 <= lshr_ln624_fu_1539_p2;
                or_ln624_reg_2390 <= or_ln624_fu_1514_p2;
                shl_ln624_reg_2405 <= shl_ln624_fu_1557_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln624_reg_2245 <= icmp_ln624_fu_1214_p2;
                select_ln624_reg_2255 <= select_ln624_fu_1234_p3;
                tmp_171_reg_2250 <= add_i_i14_lcssa_phi_fu_308(79 downto 79);
                tmp_65_reg_2235 <= tmp_65_fu_1133_p19;
                tmp_66_reg_2240 <= tmp_66_fu_1166_p19;
                tmp_87_reg_2215 <= g_fu_316(2 downto 1);
                    tmp_88_reg_2220(9 downto 8) <= tmp_88_fu_1058_p3(9 downto 8);
                tmp_reg_2225 <= tmp_fu_1067_p19;
                tmp_s_reg_2230 <= tmp_s_fu_1100_p19;
                trunc_ln576_1_reg_2210 <= trunc_ln576_1_fu_1043_p1;
                trunc_ln576_reg_2205 <= trunc_ln576_fu_1038_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                retval_0_i_i_reg_2410 <= retval_0_i_i_fu_1652_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                sub_ln624_1_reg_2378 <= sub_ln624_1_fu_1420_p2;
                sub_ln624_4_reg_2385 <= sub_ln624_4_fu_1426_p2;
                trunc_ln624_1_reg_2373 <= trunc_ln624_1_fu_1416_p1;
            end if;
        end if;
    end process;
    tmp_88_reg_2220(7 downto 0) <= "00000000";
    tmp_90_reg_2368(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_done, grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_done, icmp_ln576_fu_1026_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln576_fu_1026_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    LD_fu_1644_p1 <= pi_assign_fu_1632_p5(32 - 1 downto 0);
    add_ln576_fu_1032_p2 <= std_logic_vector(unsigned(g_fu_316) + unsigned(ap_const_lv4_1));
    add_ln624_1_fu_1526_p2 <= std_logic_vector(unsigned(sub_ln624_1_reg_2378) + unsigned(ap_const_lv6_27));
    add_ln624_2_fu_1574_p2 <= std_logic_vector(unsigned(zext_ln624_3_fu_1567_p1) + unsigned(zext_ln624_4_fu_1571_p1));
    add_ln624_3_fu_1619_p2 <= std_logic_vector(unsigned(select_ln624_1_fu_1602_p3) + unsigned(sext_ln624_2_fu_1615_p1));
    add_ln624_fu_1435_p2 <= std_logic_vector(unsigned(zext_ln624_fu_1432_p1) + unsigned(ap_const_lv7_68));
    and_ln624_fu_1470_p2 <= (select_ln624_reg_2255 and lshr_ln624_2_fu_1464_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_done)
    begin
        if ((grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_done)
    begin
        if ((grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(grp_fu_1005_p2, ap_return_preg, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_return <= grp_fu_1005_p2;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    bitcast_ln777_fu_1648_p1 <= LD_fu_1644_p1;
    cond49_i_i_in_fu_1562_p3 <= 
        lshr_ln624_reg_2400 when (icmp_ln624_3_reg_2395(0) = '1') else 
        shl_ln624_reg_2405;
    gate_0_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_0_address0;
    gate_0_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_0_ce0;
    gate_1_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_1_address0;
    gate_1_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_1_ce0;
    gate_2_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_2_address0;
    gate_2_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_2_ce0;
    gate_3_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_3_address0;
    gate_3_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_3_ce0;
    gate_4_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_4_address0;
    gate_4_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_4_ce0;
    gate_5_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_5_address0;
    gate_5_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_5_ce0;
    gate_6_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_6_address0;
    gate_6_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_6_ce0;
    gate_7_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_7_address0;
    gate_7_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_gate_7_ce0;
    grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ap_start_reg;
    grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start <= grp_mac_blocks_down_q6k5_Pipeline_VITIS_LOOP_614_4_fu_933_ap_start_reg;
    icmp_ln576_fu_1026_p2 <= "1" when (g_fu_316 = ap_const_lv4_8) else "0";
    icmp_ln624_1_fu_1455_p2 <= "1" when (signed(tmp_172_fu_1445_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln624_2_fu_1475_p2 <= "0" when (and_ln624_fu_1470_p2 = ap_const_lv56_0) else "1";
    icmp_ln624_3_fu_1520_p2 <= "1" when (signed(add_ln624_fu_1435_p2) > signed(ap_const_lv7_0)) else "0";
    icmp_ln624_fu_1214_p2 <= "1" when (trunc_ln_fu_1204_p4 = ap_const_lv56_0) else "0";
    lshr_ln624_1_fu_1580_p4 <= add_ln624_2_fu_1574_p2(56 downto 1);
    lshr_ln624_2_fu_1464_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv56_FFFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln624_1_fu_1461_p1(31-1 downto 0)))));
    lshr_ln624_fu_1539_p2 <= std_logic_vector(shift_right(unsigned(select_ln624_reg_2255),to_integer(unsigned('0' & zext_ln624_2_fu_1535_p1(31-1 downto 0)))));
    or_ln624_fu_1514_p2 <= (phi_ln624_fu_1481_p2 or phi_ln624_1_fu_1508_p2);
    phi_ln624_1_fu_1508_p2 <= (xor_ln624_fu_1495_p2 and tmp_174_fu_1501_p3);
    phi_ln624_fu_1481_p2 <= (icmp_ln624_2_fu_1475_p2 and icmp_ln624_1_fu_1455_p2);
    pi_assign_fu_1632_p5 <= (zext_ln624_5_fu_1590_p1(63 downto 32) & tmp_75_fu_1625_p3 & zext_ln624_5_fu_1590_p1(22 downto 0));
    qh_buf_0_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_0_address0;
    qh_buf_0_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_0_ce0;
    qh_buf_1_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_1_address0;
    qh_buf_1_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_1_ce0;
    qh_buf_2_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_2_address0;
    qh_buf_2_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_2_ce0;
    qh_buf_3_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_3_address0;
    qh_buf_3_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_3_ce0;
    qh_buf_4_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_4_address0;
    qh_buf_4_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_4_ce0;
    qh_buf_5_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_5_address0;
    qh_buf_5_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_5_ce0;
    qh_buf_6_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_6_address0;
    qh_buf_6_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_6_ce0;
    qh_buf_7_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_7_address0;
    qh_buf_7_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_qh_buf_7_ce0;
    ql_buf_0_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_0_address0;
    ql_buf_0_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_0_ce0;
    ql_buf_1_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_1_address0;
    ql_buf_1_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_1_ce0;
    ql_buf_2_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_2_address0;
    ql_buf_2_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_2_ce0;
    ql_buf_3_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_3_address0;
    ql_buf_3_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_3_ce0;
    ql_buf_4_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_4_address0;
    ql_buf_4_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_4_ce0;
    ql_buf_5_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_5_address0;
    ql_buf_5_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_5_ce0;
    ql_buf_6_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_6_address0;
    ql_buf_6_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_6_ce0;
    ql_buf_7_address0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_7_address0;
    ql_buf_7_ce0 <= grp_mac_blocks_down_q6k5_Pipeline_Q6K_MAC_GROUP_fu_842_ql_buf_7_ce0;
    retval_0_i_i_fu_1652_p3 <= 
        ap_const_lv32_0 when (icmp_ln624_reg_2245(0) = '1') else 
        bitcast_ln777_fu_1648_p1;
    select_ln624_1_fu_1602_p3 <= 
        ap_const_lv8_7F when (tmp_175_fu_1594_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln624_fu_1234_p3 <= 
        sub_ln624_fu_1228_p2 when (tmp_171_fu_1220_p3(0) = '1') else 
        trunc_ln_fu_1204_p4;
        sext_ln624_1_fu_1549_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln624_2_fu_1544_p2),32));

        sext_ln624_2_fu_1615_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln624_3_fu_1610_p2),8));

        sext_ln624_fu_1531_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln624_1_fu_1526_p2),32));

    shl_ln624_fu_1557_p2 <= std_logic_vector(shift_left(unsigned(select_ln624_reg_2255),to_integer(unsigned('0' & zext_ln624_6_fu_1553_p1(31-1 downto 0)))));
    sub_ln624_1_fu_1420_p2 <= std_logic_vector(signed(ap_const_lv6_38) - signed(trunc_ln624_fu_1412_p1));
    sub_ln624_2_fu_1544_p2 <= std_logic_vector(unsigned(ap_const_lv6_19) - unsigned(sub_ln624_1_reg_2378));
    sub_ln624_3_fu_1610_p2 <= std_logic_vector(unsigned(ap_const_lv7_26) - unsigned(trunc_ln624_1_reg_2373));
    sub_ln624_4_fu_1426_p2 <= std_logic_vector(unsigned(ap_const_lv6_11) - unsigned(sub_ln624_1_fu_1420_p2));
    sub_ln624_fu_1228_p2 <= std_logic_vector(unsigned(ap_const_lv56_0) - unsigned(trunc_ln_fu_1204_p4));
    tmp_171_fu_1220_p3 <= add_i_i14_lcssa_phi_fu_308(79 downto 79);
    tmp_172_fu_1445_p4 <= add_ln624_fu_1435_p2(6 downto 1);
    tmp_173_fu_1487_p3 <= add_ln624_fu_1435_p2(6 downto 6);
    tmp_174_fu_1501_p2 <= add_ln624_fu_1435_p2(6 - 1 downto 0);
    tmp_175_fu_1594_p3 <= add_ln624_2_fu_1574_p2(25 downto 25);
    tmp_65_fu_1133_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_66_fu_1166_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_75_fu_1625_p3 <= (tmp_171_reg_2250 & add_ln624_3_fu_1619_p2);
    tmp_87_fu_1047_p4 <= g_fu_316(2 downto 1);
    tmp_88_fu_1058_p3 <= (tmp_87_fu_1047_p4 & ap_const_lv8_0);
    tmp_90_fu_1374_p3 <= (trunc_ln576_1_reg_2210 & ap_const_lv2_0);
    tmp_fu_1067_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_1100_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln576_1_fu_1043_p1 <= g_fu_316(3 - 1 downto 0);
    trunc_ln576_fu_1038_p1 <= g_fu_316(1 - 1 downto 0);
    trunc_ln624_1_fu_1416_p1 <= tmp_67_fu_1405_p3(7 - 1 downto 0);
    trunc_ln624_fu_1412_p1 <= tmp_67_fu_1405_p3(6 - 1 downto 0);
    trunc_ln_fu_1204_p4 <= add_i_i14_lcssa_phi_fu_308(79 downto 24);
    xor_ln624_fu_1495_p2 <= (tmp_173_fu_1487_p3 xor ap_const_lv1_1);
    zext_ln624_1_fu_1461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln624_4_reg_2385),56));
    zext_ln624_2_fu_1535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln624_fu_1531_p1),56));
    zext_ln624_3_fu_1567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cond49_i_i_in_fu_1562_p3),57));
    zext_ln624_4_fu_1571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln624_reg_2390),57));
    zext_ln624_5_fu_1590_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln624_1_fu_1580_p4),64));
    zext_ln624_6_fu_1553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln624_1_fu_1549_p1),56));
    zext_ln624_fu_1432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln624_1_reg_2378),7));
end behav;
